CREATE OR REPLACE TRIGGER AREE_DIR_AIU
AFTER INSERT OR UPDATE
ON AREE
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
 a_azione          VARCHAR2(1) :='x';
 a_idpath          NUMBER(10);
 PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN

    IF ((:NEW.PATH_FILE_ORACLE IS NOT NULL) AND (:OLD.PATH_FILE_ORACLE IS NULL)) OR (:NEW.PATH_FILE_ORACLE<>:OLD.PATH_FILE_ORACLE) THEN
        a_azione:='I';
    END IF;

    IF (:NEW.PATH_FILE_ORACLE IS NULL) AND (:OLD.PATH_FILE_ORACLE IS NOT NULL) THEN
        a_azione:='D';
    END IF;

    IF a_azione<>'x' THEN
          P_MANAGE_ORACLEDIR(:NEW.ACRONIMO,a_azione,:NEW.PATH_FILE_ORACLE,NULL);
    END IF;


    a_azione:='x';
    a_idpath:= :NEW.ID_PATH_AREE;

     IF ((:NEW.ID_PATH_AREE IS NOT NULL) AND (:OLD.ID_PATH_AREE IS NULL)) OR (:NEW.ID_PATH_AREE<>:OLD.ID_PATH_AREE) THEN
        a_azione:='I';
    END IF;

    IF (:NEW.ID_PATH_AREE IS NULL) AND (:OLD.ID_PATH_AREE IS NOT NULL) THEN
       a_idpath :=  :OLD.ID_PATH_AREE;
        a_azione:='D';
    END IF;

    IF a_azione<>'x' THEN
          P_MANAGE_ORACLEDIR(:NEW.ACRONIMO,a_azione,NULL,a_idpath);
    END IF;

EXCEPTION
    WHEN OTHERS THEN RAISE;
END;
/


