CREATE OR REPLACE TRIGGER MODELLI_TIPI_PRATICHE_BI
/******************************************************************************
 NOME:        MODELLI_TIPI_PRATICHE_BI
 DESCRIZIONE: TRIGGER FOR CHECK DATA INTEGRITY
                          CHECK UNIQUE INTEGRITY ON PK
                          SET FUNCTIONAL INTEGRITY
                       AT INSERT OR UPDATE ON TABLE MODELLI_TIPI_PRATICHE
 ECCEZIONI:  -20007, IDENTIFICAZIONE CHIAVE PRESENTE IN TABLE
 ANNOTAZIONI: -
 REVISIONI:
 REV. DATA       AUTORE DESCRIZIONE
 ---- ---------- ------ ------------------------------------------------------
    0 __/__/____ __
******************************************************************************/
   BEFORE INSERT OR UPDATE ON MODELLI_TIPI_PRATICHE
FOR EACH ROW
DECLARE
   INTEGRITY_ERROR  EXCEPTION;
   ERRNO            INTEGER;
   ERRMSG           CHAR(200);
   DUMMY            INTEGER;
   FOUND            BOOLEAN;
BEGIN
   BEGIN  -- CHECK DATA INTEGRITY
      --  COLUMN "ID_MTP" USES SEQUENCE GD4.SEQ_ID_MTP
      IF :NEW.ID_MTP IS NULL AND NOT DELETING THEN
         SELECT SEQ_ID_MTP.NEXTVAL
           INTO :NEW.ID_MTP
           FROM DUAL;
      END IF;
      BEGIN  -- CHECK UNIQUE INTEGRITY ON PK OF "MODELLI_TIPI_PRATICHE"
         IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 AND NOT DELETING THEN
            DECLARE
            CURSOR CPK_MODELLI_TIPI_PRATICHE(VAR_ID_MTP NUMBER) IS
               SELECT 1
                 FROM   MODELLI_TIPI_PRATICHE
                WHERE  ID_MTP = VAR_ID_MTP;
            MUTATING         EXCEPTION;
            PRAGMA EXCEPTION_INIT(MUTATING, -4091);
            BEGIN
               IF :NEW.ID_MTP IS NOT NULL THEN
                  OPEN  CPK_MODELLI_TIPI_PRATICHE(:NEW.ID_MTP);
                  FETCH CPK_MODELLI_TIPI_PRATICHE INTO DUMMY;
                  FOUND := CPK_MODELLI_TIPI_PRATICHE%FOUND;
                  CLOSE CPK_MODELLI_TIPI_PRATICHE;
                  IF FOUND THEN
                     ERRNO  := -20007;
                     ERRMSG := 'Identificazione "'||
                               :NEW.ID_MTP||
                               '" gia'' presente in MODELLI_TIPI_PRATICHE. La registrazione  non puo'' essere inserita.';
                     RAISE INTEGRITY_ERROR;
                  END IF;
               END IF;
            EXCEPTION
               WHEN MUTATING THEN NULL;  -- IGNORA CHECK SU UNIQUE PK INTEGRITY
            END;
         END IF;
      END;
      NULL;
   END;
   BEGIN  -- SET FUNCTIONAL INTEGRITY
      IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 THEN
         INTEGRITYPACKAGE.NEXTNESTLEVEL;
         BEGIN  -- GLOBAL FUNCTIONAL INTEGRITY AT LEVEL 0
            /* NONE */ NULL;
         END;
         INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
      END IF;
      INTEGRITYPACKAGE.NEXTNESTLEVEL;
      BEGIN  -- FULL FUNCTIONAL INTEGRITY AT ANY LEVEL
         /* NONE */ NULL;
      END;
      INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
   END;
EXCEPTION
   WHEN INTEGRITY_ERROR THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
   WHEN OTHERS THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE;
END;
/* END TRIGGER: MODELLI_TIPI_PRATICHE_BI */
/


