CREATE OR REPLACE TRIGGER OGGETTI_FILE_TD
   BEFORE DELETE
   ON OGGETTI_FILE
   FOR EACH ROW
BEGIN
  DELETE FROM IMPRONTE_FILE
  WHERE ID_DOCUMENTO=:OLD.ID_DOCUMENTO AND FILENAME=:OLD.FILENAME;
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE;
END;
/


