CREATE OR REPLACE TRIGGER OGGETTI_FILE_LOG_TIU
BEFORE INSERT
ON OGGETTI_FILE_LOG
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
BEGIN
   IF INSTR(:NEW.PATH_FILE,'LOG')=0 AND :NEW.PATH_FILE IS NOT NULL THEN
      :NEW.PATH_FILE := :NEW.PATH_FILE||'\LOG_'||TO_CHAR(:NEW.ID_LOG)  ;
   END IF;

   EXCEPTION
     WHEN OTHERS THEN
       RAISE;
END;
/


