CREATE OR REPLACE TRIGGER OPERAZIONI_DI_INOLTRO_TIU
/******************************************************************************
 NOME:        OPERAZIONI_DI_INOLTRO_TIU
 DESCRIZIONE: TRIGGER FOR CHECK DATA INTEGRITY
                          CHECK UNIQUE INTEGRITY ON PK
                          SET FUNCTIONAL INTEGRITY
                       AT INSERT OR UPDATE ON TABLE OPERAZIONI_DI_INOLTRO
 ECCEZIONI:  -20007, IDENTIFICAZIONE CHIAVE PRESENTE IN TABLE
 ANNOTAZIONI: -
 REVISIONI:
 REV. DATA       AUTORE DESCRIZIONE
 ---- ---------- ------ ------------------------------------------------------
    0 __/__/____ __
******************************************************************************/
   BEFORE INSERT OR UPDATE ON OPERAZIONI_DI_INOLTRO
FOR EACH ROW
DECLARE
   INTEGRITY_ERROR  EXCEPTION;
   ERRNO            INTEGER;
   ERRMSG           CHAR(200);
   DUMMY            INTEGER;
   FOUND            BOOLEAN;
BEGIN
   BEGIN  -- CHECK DATA INTEGRITY
      --  COLUMN "ID_OP" USES SEQUENCE GD4.SEQ_ID_OP
      IF :NEW.ID_OP IS NULL AND NOT DELETING THEN
         SELECT SEQ_ID_OP.NEXTVAL
           INTO :NEW.ID_OP
           FROM DUAL;
      END IF;
      BEGIN  -- CHECK UNIQUE INTEGRITY ON PK OF "OPERAZIONI_DI_INOLTRO"
         IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 AND NOT DELETING THEN
            DECLARE
            CURSOR CPK_OPERAZIONI_DI_INOLTRO(VAR_ID_OP NUMBER) IS
               SELECT 1
                 FROM   OPERAZIONI_DI_INOLTRO
                WHERE  ID_OP = VAR_ID_OP;
            MUTATING         EXCEPTION;
            PRAGMA EXCEPTION_INIT(MUTATING, -4091);
            BEGIN
               IF :NEW.ID_OP IS NOT NULL THEN
                  OPEN  CPK_OPERAZIONI_DI_INOLTRO(:NEW.ID_OP);
                  FETCH CPK_OPERAZIONI_DI_INOLTRO INTO DUMMY;
                  FOUND := CPK_OPERAZIONI_DI_INOLTRO%FOUND;
                  CLOSE CPK_OPERAZIONI_DI_INOLTRO;
                  IF FOUND THEN
                     ERRNO  := -20007;
                     ERRMSG := 'Identificazione "'||
                               :NEW.ID_OP||
                               '" gia'' presente in OPERAZIONI_DI_INOLTRO. La registrazione  non puo'' essere inserita.';
                     RAISE INTEGRITY_ERROR;
                  END IF;
               END IF;
            EXCEPTION
               WHEN MUTATING THEN NULL;  -- IGNORA CHECK SU UNIQUE PK INTEGRITY
            END;
         END IF;
      END;
      NULL;
   END;
   BEGIN  -- SET FUNCTIONAL INTEGRITY
      IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 THEN
         INTEGRITYPACKAGE.NEXTNESTLEVEL;
         BEGIN  -- GLOBAL FUNCTIONAL INTEGRITY AT LEVEL 0
            /* NONE */ NULL;
         END;
         INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
      END IF;
      INTEGRITYPACKAGE.NEXTNESTLEVEL;
      BEGIN  -- FULL FUNCTIONAL INTEGRITY AT ANY LEVEL
         /* NONE */ NULL;
      END;
      INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
   END;
EXCEPTION
   WHEN INTEGRITY_ERROR THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
   WHEN OTHERS THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE;
END;
/* END TRIGGER: OPERAZIONI_DI_INOLTRO_TIU */
/


