CREATE OR REPLACE TRIGGER ORDINAMENTI_CARTELLA_TIU
/******************************************************************************
 NOME:        ORDINAMENTI_CARTELLA_TIU
 DESCRIZIONE: TRIGGER FOR CHECK DATA INTEGRITY
                          CHECK UNIQUE INTEGRITY ON PK
                          SET FUNCTIONAL INTEGRITY
                       AT INSERT OR UPDATE ON TABLE ORDINAMENTI_CARTELLA
 ECCEZIONI:  -20007, IDENTIFICAZIONE CHIAVE PRESENTE IN TABLE
 ANNOTAZIONI: -
 REVISIONI:
 REV. DATA       AUTORE DESCRIZIONE
 ---- ---------- ------ ------------------------------------------------------
    0 __/__/____ __
******************************************************************************/
   BEFORE INSERT OR UPDATE ON ORDINAMENTI_CARTELLA
FOR EACH ROW
DECLARE
   INTEGRITY_ERROR  EXCEPTION;
   ERRNO            INTEGER;
   ERRMSG           CHAR(200);
   DUMMY            INTEGER;
   FOUND            BOOLEAN;
BEGIN
   BEGIN  -- CHECK DATA INTEGRITY
      --  COLUMN "ID_ORDINAMENTOCARTELLA" USES SEQUENCE ORCA_SQ
      IF :NEW.ID_ORDINAMENTOCARTELLA IS NULL AND NOT DELETING THEN
         SELECT ORCA_SQ.NEXTVAL
           INTO :NEW.ID_ORDINAMENTOCARTELLA
           FROM DUAL;
      END IF;
      BEGIN  -- CHECK UNIQUE INTEGRITY ON PK OF "ORDINAMENTI_CARTELLA"
         IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 AND NOT DELETING THEN
            DECLARE
            CURSOR CPK_ORDINAMENTI_CARTELLA(VAR_ID_ORDINAMENTOCARTELLA NUMBER) IS
               SELECT 1
                 FROM   ORDINAMENTI_CARTELLA
                WHERE  ID_ORDINAMENTOCARTELLA = VAR_ID_ORDINAMENTOCARTELLA;
            MUTATING         EXCEPTION;
            PRAGMA EXCEPTION_INIT(MUTATING, -4091);
            BEGIN
               IF :NEW.ID_ORDINAMENTOCARTELLA IS NOT NULL THEN
                  OPEN  CPK_ORDINAMENTI_CARTELLA(:NEW.ID_ORDINAMENTOCARTELLA);
                  FETCH CPK_ORDINAMENTI_CARTELLA INTO DUMMY;
                  FOUND := CPK_ORDINAMENTI_CARTELLA%FOUND;
                  CLOSE CPK_ORDINAMENTI_CARTELLA;
                  IF FOUND THEN
                     ERRNO  := -20007;
                     ERRMSG := 'Identificazione "'||
                               :NEW.ID_ORDINAMENTOCARTELLA||
                               '" gia'' presente in ORDINAMENTI_CARTELLA. La registrazione  non puo'' essere inserita.';
                     RAISE INTEGRITY_ERROR;
                  END IF;
               END IF;
            EXCEPTION
               WHEN MUTATING THEN NULL;  -- IGNORA CHECK SU UNIQUE PK INTEGRITY
            END;
         END IF;
      END;
      NULL;
   END;
   BEGIN  -- SET FUNCTIONAL INTEGRITY
      IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 THEN
         INTEGRITYPACKAGE.NEXTNESTLEVEL;
         BEGIN  -- GLOBAL FUNCTIONAL INTEGRITY AT LEVEL 0
            /* NONE */ NULL;
         END;
         INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
      END IF;
      INTEGRITYPACKAGE.NEXTNESTLEVEL;
      BEGIN  -- FULL FUNCTIONAL INTEGRITY AT ANY LEVEL
         /* NONE */ NULL;
      END;
      INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
   END;
EXCEPTION
   WHEN INTEGRITY_ERROR THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
   WHEN OTHERS THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE;
END;
/* END TRIGGER: ORDINAMENTI_CARTELLA_TIU */
/


