CREATE OR REPLACE TRIGGER PERSONALIZZAZIONI_TIU
/******************************************************************************
 NOME:        PERSONALIZZAZIONI_TIU
 DESCRIZIONE: TRIGGER FOR CHECK DATA INTEGRITY
                          CHECK UNIQUE INTEGRITY ON PK
                          SET FUNCTIONAL INTEGRITY
                       AT INSERT OR UPDATE ON TABLE PERSONALIZZAZIONI
 ECCEZIONI:  -20007, IDENTIFICAZIONE CHIAVE PRESENTE IN TABLE
 ANNOTAZIONI: -
 REVISIONI:
 REV. DATA       AUTORE DESCRIZIONE
 ---- ---------- ------ ------------------------------------------------------
    0 __/__/____ __
******************************************************************************/
   BEFORE INSERT OR UPDATE ON PERSONALIZZAZIONI
FOR EACH ROW
DECLARE
   INTEGRITY_ERROR  EXCEPTION;
   ERRNO            INTEGER;
   ERRMSG           CHAR(200);
   DUMMY            INTEGER;
   FOUND            BOOLEAN;
BEGIN
   BEGIN  -- CHECK DATA INTEGRITY
      --  COLUMN "ID_PERSONALIZZAZIONE" USES SEQUENCE PERS_SQ
      IF :NEW.ID_PERSONALIZZAZIONE IS NULL AND NOT DELETING THEN
         SELECT PERS_SQ.NEXTVAL
           INTO :NEW.ID_PERSONALIZZAZIONE
           FROM DUAL;
      END IF;
      BEGIN  -- CHECK UNIQUE INTEGRITY ON PK OF "PERSONALIZZAZIONI"
         IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 AND NOT DELETING THEN
            DECLARE
            CURSOR CPK_PERSONALIZZAZIONI(VAR_ID_PERSONALIZZAZIONE NUMBER) IS
               SELECT 1
                 FROM   PERSONALIZZAZIONI
                WHERE  ID_PERSONALIZZAZIONE = VAR_ID_PERSONALIZZAZIONE;
            MUTATING         EXCEPTION;
            PRAGMA EXCEPTION_INIT(MUTATING, -4091);
            BEGIN
               IF :NEW.ID_PERSONALIZZAZIONE IS NOT NULL THEN
                  OPEN  CPK_PERSONALIZZAZIONI(:NEW.ID_PERSONALIZZAZIONE);
                  FETCH CPK_PERSONALIZZAZIONI INTO DUMMY;
                  FOUND := CPK_PERSONALIZZAZIONI%FOUND;
                  CLOSE CPK_PERSONALIZZAZIONI;
                  IF FOUND THEN
                     ERRNO  := -20007;
                     ERRMSG := 'Identificazione "'||
                               :NEW.ID_PERSONALIZZAZIONE||
                               '" gia'' presente in PERSONALIZZAZIONI. La registrazione  non puo'' essere inserita.';
                     RAISE INTEGRITY_ERROR;
                  END IF;
               END IF;
            EXCEPTION
               WHEN MUTATING THEN NULL;  -- IGNORA CHECK SU UNIQUE PK INTEGRITY
            END;
         END IF;
      END;
      NULL;
   END;
   BEGIN  -- SET FUNCTIONAL INTEGRITY
      IF INTEGRITYPACKAGE.GETNESTLEVEL = 0 THEN
         INTEGRITYPACKAGE.NEXTNESTLEVEL;
         BEGIN  -- GLOBAL FUNCTIONAL INTEGRITY AT LEVEL 0
            /* NONE */ NULL;
         END;
         INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
      END IF;
      INTEGRITYPACKAGE.NEXTNESTLEVEL;
      BEGIN  -- FULL FUNCTIONAL INTEGRITY AT ANY LEVEL
         /* NONE */ NULL;
      END;
      INTEGRITYPACKAGE.PREVIOUSNESTLEVEL;
   END;
EXCEPTION
   WHEN INTEGRITY_ERROR THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
   WHEN OTHERS THEN
        INTEGRITYPACKAGE.INITNESTLEVEL;
        RAISE;
END;
/* END TRIGGER: PERSONALIZZAZIONI_TIU */
/


