CREATE OR REPLACE PACKAGE ANALISI_SPAZIOFILE AS
    /* PARAMETRI PROTOCOLLO */
    P_ABILITA_PROTOCOLLO       NUMBER(1) := 0 ;
    P_DATA_PROTOCOLLO_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_PROTOCOLLO_A       VARCHAR2(10) := '01/01/2900';
    P_UTENTI_PROTOCOLLANTI  VARCHAR2(3200) :=NULL; --utenti ad4 separati da #

     /* PARAMETRI PROTOCOLLO INTEROP */
    P_ABILITA_PROTOCOLLO_INTERO     NUMBER(1) := 0 ;
    P_DATA_PROTOCOLLO_INTERO_DA  VARCHAR2(10) := '01/01/1900';
    P_DATA_PROTOCOLLO_INTERO_A    VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI PROTOCOLLO MEMO_PROTO */
    P_ABILITA_PROTOCOLLO_MEMO     NUMBER(1) := 0 ;
    P_DATA_PROTOCOLLO_MEMO_DA  VARCHAR2(10) := '01/01/1900';
    P_DATA_PROTOCOLLO_MEMO_A    VARCHAR2(10) := '01/01/2900';


     /* PARAMETRI  LETTERA USCITA  */
    P_ABILITA_LETTERA_USCITA     NUMBER(1) := 0 ;
    P_DATA_LETTERA_USCITA_DA  VARCHAR2(10) := '01/01/1900';
    P_DATA_LETTERA_USCITA_A    VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  DETERMINA  */
    P_ABILITA_DETERMINA     NUMBER(1) := 0 ;
    P_DATA_DETERMINA_DA  VARCHAR2(10) := '01/01/1900';
    P_DATA_DETERMINA_A    VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  DETERMINA2.0  */
    P_ABILITA_DETERMINA_20     NUMBER(1) := 0 ;
    P_DATA_DETERMINA_20_DA  VARCHAR2(10) := '01/01/1900';
    P_DATA_DETERMINA_20_A    VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  DELIBERA  */
    P_ABILITA_DELIBERA        NUMBER(1) := 0 ;
    P_DATA_DELIBERA_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_DELIBERA_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  DELIBERA2.0  */
    P_ABILITA_DELIBERA_20        NUMBER(1) := 0 ;
    P_DATA_DELIBERA_20_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_DELIBERA_20_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  REVISIONE ATTI  */
    P_ABILITA_REVISIONE_ATTI       NUMBER(1) := 0 ;
    P_DATA_REVISIONE_ATTI_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_REVISIONE_ATTI_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  REVISIONE PROTOCOLLO  */
    P_ABILITA_REVISIONE_PROTO     NUMBER(1) := 0 ;
    P_DATA_REVISIONE_PROTO_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_REVISIONE_PROTO_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  ALBO */
    P_ABILITA_ALBO     NUMBER(1) := 0 ;
    P_DATA_ALBO_DA     VARCHAR2(10) := '01/01/1900';
    P_DATA_ALBO_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  FASCICOLO_PERSONALE_FIRENZE */
    P_ABILITA_FASC_PERS_FI     NUMBER(1) := 0 ;
    P_DATA_FASC_PERS_FI_DA    VARCHAR2(10) := '01/01/1900';
    P_DATA_FASC_PERS_FI_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  PEC ENTRATA */
    P_ABILITA_PEC_ENTRATA   NUMBER(1) := 0 ;
    P_DATA_PEC_ENTRATA_DA    VARCHAR2(10) := '01/01/1900';
    P_DATA_PEC_ENTRATA_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  PEC USCITA*/
    P_ABILITA_PEC_USCITA   NUMBER(1) := 0 ;
    P_DATA_PEC_USCITA_DA    VARCHAR2(10) := '01/01/1900';
    P_DATA_PEC_USCITA_A       VARCHAR2(10) := '01/01/2900';

     /* PARAMETRI  RICEVUTA PEC USCITA*/
    P_ABILITA_RICEVUTE_PEC_USCITA   NUMBER(1) := 0 ;
    P_DATA_RICEVUTE_PEC_USCITA_DA    VARCHAR2(10) := '01/01/1900';
    P_DATA_RICEVUTE_PEC_USCITA_A       VARCHAR2(10) := '01/01/2900';

    /* PARAMETRI  FATTURE_ELETTRONICHE */
    P_ABILITA_FATT_ELETTRONICHE         NUMBER(1) := 0 ;
    P_DATA_FATT_ELETTRONICHE_DA       VARCHAR2(10) := '01/01/1900';
    P_DATA_FATT_ELETTRONICHE_A         VARCHAR2(10) := '01/01/2900';


    P_ABILITA_SOLO_CONSERVAZIONE    NUMBER(1):=0;


    PROCEDURE ABILITA_PROTOCOLLO(P_DA VARCHAR2, P_A VARCHAR2, P_LISTAUTE_PROTOCOLLANTE VARCHAR2 DEFAULT NULL);
    PROCEDURE ABILITA_PROTOCOLLO_INTERO(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_MEMO_PROTOCOLLO(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_LETTERA_USCITA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_DETERMINA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_DELIBERA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_REVISIONE_ATTI(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_REVISIONE_PROTO(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_ALBO(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_FASCICOLO_PERS_FIRENZE(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_PEC_ENTRATA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_PEC_USCITA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_RICEVUTE_PEC_USCITA(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_DETERMINA_20(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_DELIBERA_20(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_FATT_ELETTRONICHE(P_DA VARCHAR2, P_A VARCHAR2);
    PROCEDURE ABILITA_SOLO_CONSERVAZIONE(P_DA VARCHAR2, P_A VARCHAR2);

    PROCEDURE ANALIZZA;
END ANALISI_SPAZIOFILE;
/

