CREATE OR REPLACE PACKAGE GDM_UTILITY AS
   FUNCTION PARSEQUERYSTRING (P_QRYSTR IN VARCHAR2,P_CAMPO IN VARCHAR2) RETURN VARCHAR2;
   FUNCTION SOVRASCRIVI_SEMPRE (P_AREA IN VARCHAR2,P_TIPODOC IN VARCHAR2,P_STATUS IN VARCHAR2) RETURN VARCHAR2;
   FUNCTION PARSEBODY_CF (P_IDDOCUMENTO IN NUMBER,P_BODY IN VARCHAR2) RETURN VARCHAR2;
   PROCEDURE extract_file (idobj IN NUMBER, idlog IN NUMBER);
   PROCEDURE MKDIR(A_PERCORSO VARCHAR2);
   PROCEDURE RMDIR(A_PERCORSO VARCHAR2, A_FILE NUMBER DEFAULT 0);
   PROCEDURE CHMOD(A_PERCORSO VARCHAR2) ;
   FUNCTION F_MULTILINGUA(P_ESPRESSIONE IN  DIZIONARIO_LINGUA.ESPRESSIONE%TYPE,P_LINGUA IN DIZIONARIO_LINGUA.LINGUA%TYPE) RETURN VARCHAR2;
END GDM_UTILITY;
/

