CREATE OR REPLACE PACKAGE gdm_oggetti_file_log
AS
FUNCTION F_GET_ID_OGGETTO(P_IDDOCUMENTO NUMBER,P_NOMEFILE VARCHAR2,P_IDLOG_OR_VERSION NUMBER) RETURN VARCHAR2;
FUNCTION F_GET_HASH(P_IDDOCUMENTO NUMBER,P_NOMEFILE VARCHAR2,P_IDLOGORVERSION NUMBER) RETURN VARCHAR2;
END;
/

