CREATE OR REPLACE PACKAGE GDM_QUERY AS
    FUNCTION CREA_QUERY(A_AREA VARCHAR2, A_MODELLO VARCHAR2, A_NOME_QUERY VARCHAR2, A_FILTRO VARCHAR2, A_UTENTE VARCHAR2, A_ID_CARTELLA_PADRE NUMBER DEFAULT NULL) RETURN NUMBER;
    FUNCTION CREA_QUERY(A_AREA VARCHAR2, A_MODELLO VARCHAR2, A_NOME_QUERY VARCHAR2, A_FILTRO VARCHAR2, A_UTENTE VARCHAR2,  A_ID_CARTELLA_PADRE NUMBER DEFAULT NULL, A_CREA_RECORD_ORIZZONTALE NUMBER) RETURN NUMBER;
    PROCEDURE ADDCAMPO(P_AREA VARCHAR2, P_MODELLO VARCHAR2, P_NOME_CAMPO VARCHAR2, P_VALORE CLOB);
    PROCEDURE ADDCAMPO(P_AREA VARCHAR2, P_MODELLO VARCHAR2, P_NOME_CAMPO VARCHAR2, P_VALORE NUMBER);
    PROCEDURE ADDCAMPO(P_AREA VARCHAR2, P_MODELLO VARCHAR2, P_NOME_CAMPO VARCHAR2, P_VALORE DATE);
    PROCEDURE RESETCAMPO(P_AREA VARCHAR2, P_MODELLO VARCHAR2, P_NOME_CAMPO VARCHAR2);
    PROCEDURE RESETCAMPI;
END GDM_QUERY;
/

