CREATE OR REPLACE FUNCTION F_ALLINEA_MODCART( A_IDTIPODOC VARCHAR2)
RETURN VARCHAR2 IS
/* VERSIONE 1.0 CREATA IL 12/05/2005 DA ANDREA */
/* ALLINEA LE TABELLE DATI, DATI_MODELLO E CAMPI_DOCUMENTO PER IL DATO $ACTIONKEY
 * PER LA GESTINONE DEI MODELLI DI TIPO CARTELLA
 * TORNA 1 SE VA TUTTO BENE ALTRIMENTI DA UN MESSAGGIO DI ERRORE */
   S_AREA VARCHAR2(10) := 'GDMSYS';
   S_DATO VARCHAR2(15) := '$ACTIONKEY';
   S_TIPO_CAMPO     VARCHAR2(1) := 'S';
   S_TIPO_ACCESSO VARCHAR2(1) := 'S';
   N_LUNG         NUMBER(10)   ;
   DEP             NUMBER(1);
   IDCAMPO        NUMBER(10);
   CURSOR C_1 (SAREA VARCHAR2, SDATO VARCHAR2) IS
   SELECT CODICE_MODELLO , ID_TIPODOC
    FROM MODELLI MO
   WHERE NOT EXISTS (SELECT 1 FROM DATI_MODELLO DM
                    WHERE DM.AREA = SAREA   -- 'GDMSYS''
                    AND DM.DATO = SDATO   -- '$ACTIONKEY''
                   AND DM.CODICE_MODELLO = MO.CODICE_MODELLO  )
     AND TIPO_USO = 'C'
     AND ID_TIPODOC IS NOT NULL
    AND A_IDTIPODOC IS NULL
    UNION ALL
   SELECT CODICE_MODELLO , ID_TIPODOC
    FROM MODELLI MO
   WHERE NOT EXISTS (SELECT 1 FROM DATI_MODELLO DM
                    WHERE DM.AREA = SAREA   -- 'GDMSYS''
                    AND DM.DATO = SDATO   -- '$ACTIONKEY''
                   AND DM.CODICE_MODELLO = MO.CODICE_MODELLO  )
     AND TIPO_USO = 'C'
     AND ID_TIPODOC = A_IDTIPODOC
   ;
 BEGIN
    BEGIN
       SELECT LUNGHEZZA
        INTO N_LUNG
      FROM DATI
      WHERE AREA = S_AREA
        AND DATO = S_DATO;
      EXCEPTION
       WHEN NO_DATA_FOUND THEN
             BEGIN
            INSERT INTO DATI (AREA,   DATO, TIPO, LUNGHEZZA, DECIMALI)
                      VALUES (S_AREA, S_DATO, 'S', 9999999999, 0);
             N_LUNG := 9999999999;
            EXCEPTION
             WHEN OTHERS THEN
                RETURN '-20990'||SQLERRM;
          END;
    END;
   FOR C1 IN C_1(S_AREA , S_DATO )  LOOP
   BEGIN
      BEGIN
         INSERT INTO DATI_MODELLO
                     (AREA, CODICE_MODELLO, DATO,  LUNGHEZZA, DECIMALI, TIPO_CAMPO, TIPO_ACCESSO)
            VALUES (S_AREA, C1.CODICE_MODELLO, S_DATO, N_LUNG,0,S_TIPO_CAMPO,S_TIPO_ACCESSO);
        EXCEPTION
          WHEN OTHERS THEN
             RETURN '-20991'||SQLERRM;
     END;
      BEGIN
         SELECT 1
          INTO DEP
            FROM CAMPI_DOCUMENTO
           WHERE ID_TIPODOC = C1.ID_TIPODOC
           AND NOME = S_DATO;
       EXCEPTION
         WHEN NO_DATA_FOUND THEN
         BEGIN
            BEGIN
              SELECT CADO_SQ.NEXTVAL
                INTO IDCAMPO
               FROM DUAL;
           END;
           BEGIN
                 INSERT INTO CAMPI_DOCUMENTO
                       (ID_CAMPO, ID_TIPODOC, NOME, OBBLIGATORIO, DATA_AGGIORNAMENTO, UTENTE_AGGIORNAMENTO)
               VALUES (IDCAMPO , C1.ID_TIPODOC, S_DATO, 'N', SYSDATE,'GDM');
           END;
           BEGIN
               UPDATE DATI_MODELLO SET ID_CAMPO = IDCAMPO
              WHERE AREA = S_AREA
                 AND DATO = S_DATO
                AND CODICE_MODELLO = C1.CODICE_MODELLO ;
           END;
           EXCEPTION
             WHEN OTHERS THEN
          RETURN SQLERRM;
         END;
     END;
   END;
    END LOOP;
 RETURN '1';
 END F_ALLINEA_MODCART ;
/

