CREATE OR REPLACE FUNCTION F_ALLINEA_IDCAMPO(P_AREA VARCHAR2,P_MODELLO VARCHAR2)
RETURN NUMBER IS
       CURSOR C_CAMPI IS
         SELECT ID_CAMPO,NOME
           FROM MODELLI, CAMPI_DOCUMENTO
          WHERE codice_modello=P_MODELLO AND area=P_AREA
            AND CAMPI_DOCUMENTO.ID_TIPODOC=MODELLI.ID_TIPODOC;
BEGIN
   FOR CCAMPI IN C_CAMPI LOOP
       UPDATE DATI_MODELLO
       SET ID_CAMPO=CCAMPI.ID_CAMPO
       WHERE codice_modello=P_MODELLO AND AREA=P_AREA AND DATO=CCAMPI.NOME;
   END LOOP;
   RETURN 1;
   EXCEPTION WHEN OTHERS THEN
             ROLLBACK;
             RAISE_APPLICATION_ERROR('-20999','PROBLEMI IN ALLINEA IDCAMPO. DESCRIZIONE ERRORE: '||SQLERRM);
             RETURN 0;
END F_ALLINEA_IDCAMPO;
/

