CREATE OR REPLACE FUNCTION F_AREA_DATO(A_AREA VARCHAR2, A_DATO VARCHAR2)
RETURN VARCHAR2 IS
       D_AREA DATI.LABEL%TYPE := A_DATO;
BEGIN
    BEGIN
      SELECT AREA
       INTO D_AREA
       FROM DATI
       WHERE AREA = A_AREA
         AND DATO=A_DATO;
   EXCEPTION WHEN NO_DATA_FOUND THEN
      D_AREA:='X';
   END;
   IF D_AREA='X' AND INSTR(A_AREA,'.')>0 THEN
      RETURN F_AREA_DATO(SUBSTR(A_AREA,1,INSTR(A_AREA,'.',-1)-1),A_DATO);
   END IF;
    RETURN D_AREA;
END F_AREA_DATO;
/

