CREATE OR REPLACE FUNCTION F_ASSEGNA
( P_TIPO_OGGETTO IN VARCHAR2
, P_OGGETTO IN VARCHAR2
, P_TIPO_ABILITAZIONE IN VARCHAR2
, P_UTENTE IN VARCHAR2
, P_RUOLO IN VARCHAR2 DEFAULT NULL
, P_AUTORE IN VARCHAR2
, P_ACCESSO IN VARCHAR2 DEFAULT 'S'
, P_DAL IN VARCHAR2 DEFAULT NULL
, P_AL IN VARCHAR2 DEFAULT NULL
, P_FUNZIONE IN VARCHAR2 DEFAULT NULL)
RETURN NUMBER
IS
RETVAL NUMBER;
BEGIN
   RETVAL := SI4_COMPETENZA.ASSEGNA(P_TIPO_OGGETTO, P_OGGETTO, P_TIPO_ABILITAZIONE,
               P_UTENTE, P_RUOLO, P_AUTORE, P_ACCESSO, P_DAL, P_AL, P_FUNZIONE);
   RETURN RETVAL;
END;
/

