CREATE OR REPLACE FUNCTION F_CAMPO(P_CAMPO VARCHAR2, P_TIPODOC NUMBER)
RETURN NUMBER IS
/*  BY ANDREA*/
   N_CAMPO NUMBER(20);
 BEGIN
        SELECT C.ID_CAMPO
        INTO N_CAMPO
        FROM CAMPI_DOCUMENTO C
         WHERE C.ID_TIPODOC = P_TIPODOC
         AND C.NOME = P_CAMPO;
      RETURN N_CAMPO;
   EXCEPTION
     WHEN OTHERS THEN
      RETURN 0;
 END  F_CAMPO ;
/

