CREATE OR REPLACE FUNCTION F_CM_AREA_CR_FROM_IDDOC(A_IDDOC NUMBER)
RETURN VARCHAR2 IS
/*  BY MANNY*/
   DESCR VARCHAR2(2000);
 BEGIN
   BEGIN
      SELECT NOME||'@'||AREA||'@'||CODICE_RICHIESTA
      INTO DESCR
      FROM DOCUMENTI D, TIPI_DOCUMENTO TP
     WHERE D.ID_TIPODOC=TP.ID_TIPODOC AND D.ID_DOCUMENTO=A_IDDOC
   ;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN '';
   END;
   RETURN DESCR;
 END F_CM_AREA_CR_FROM_IDDOC;
/

