CREATE OR REPLACE FUNCTION F_CODICEMOD_FROM_IDQUERY(A_QUERY NUMBER)
RETURN VARCHAR2 IS
/*  BY MANNY*/
   CM MODELLI.CODICE_MODELLO%TYPE;
 BEGIN
   BEGIN
    SELECT M.CODICE_MODELLO
      INTO CM
      FROM QUERY Q, DOCUMENTI D, MODELLI M
     WHERE Q.ID_QUERY=A_QUERY AND
          Q.ID_DOCUMENTO_PROFILO=D.ID_DOCUMENTO AND
          D.ID_TIPODOC=M.ID_TIPODOC
      ;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN NULL;
   END;
   RETURN CM;
 END F_CODICEMOD_FROM_IDQUERY;
/

