CREATE OR REPLACE FUNCTION F_CODICEMOD_FROM_IDCARTELLA(A_CARTELLA NUMBER)
RETURN VARCHAR2 IS
/*  BY MANNY*/
   CM MODELLI.CODICE_MODELLO%TYPE;
 BEGIN
   BEGIN
    SELECT M.CODICE_MODELLO
      INTO CM
      FROM CARTELLE C, DOCUMENTI D, MODELLI M
     WHERE C.ID_CARTELLA=A_CARTELLA AND
          C.ID_DOCUMENTO_PROFILO=D.ID_DOCUMENTO AND
          D.ID_TIPODOC=M.ID_TIPODOC
      ;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN NULL;
   END;
   RETURN CM;
 END F_CODICEMOD_FROM_IDCARTELLA ;
/

