CREATE OR REPLACE FUNCTION F_CREA_VISTA_TIPODOC (A_AREA VARCHAR2, A_CODMOD VARCHAR2, A_NOME VARCHAR2 DEFAULT NULL) RETURN VARCHAR2 IS
/* VERSIONE 1.1 MODIFICATA IL 30/12/2004 DA ANDREA AGGIUNTO CONTROLLO FLAG_VIEW = 'S' SUI CAMPI */
/* VERSIONE 1.2 MODIFICATA IL 01/02/2005 DA ANDREA ALLARGATA LA DIMENSIONE DELLE VARIABILI */
/* VERSIONE 1.3 MODIFICATA IL 09/02/2005 DA ANDREA SETTANDO IL NOME CON IL CODICE TIPO_DOCUMENTO*/
/* VERSIONE 1.5 MODIFICATA IL 31/03/2005 DA ANDREA IL NOME DELLA VIEW E PASSATO COME PARAMETRO */
/* VERSIONE 1.6 MODIFICATA IL 04/05/2005 DA ANDREA MODIFICATO IL COMMENTO ALLA VISTA */
/* VERSIONE 1.7 MODIFICATA IL 23/11/2005 DA MARIKA AGGIUNTE VIRGOLETTE PER COLONNE CON '$' E CONTROLLO IN_USO!='N'*/
/* VERSIONE 1.8 MODIFICATA IL 23/11/2005 DA MARIKA AGGIUNTA MODIFICA PER DATI DI AREE DIVERSE */
/* VERSIONE 1.9 MODIFICATA IL 27/03/2006 DA MARIKA AGGIUNTO VALORE DI RITORNO 3 PER CAMPI PROTETTI */
/* VERSIONE 1.9 MODIFICATA IL 05/03/2008 DA MARCO PER GESTIONE TABELLE ORIZZONTALI */
/*RITORNA 1 SE VA TUTTO BENE
         0 SE IL NOME E TROPPO LUNGO
         2 SE IL NOME E GIA IN USO
         3 SE UN CAMPO HA LO STESSO NOME DI UNA DELLE COLONNE STANDARD*/
   nometabella   VARCHAR2 (30);
   s_valore      VARCHAR2 (4000);
BEGIN
   nometabella := f_nome_tabella(A_AREA, A_CODMOD);
   IF f_esiste_tabella (nometabella) = 1
   THEN
      s_valore := F_CREA_VISTA_TIPODOC_oriz (A_AREA, A_CODMOD, A_NOME);
   ELSE
      s_valore := F_CREA_VISTA_TIPODOC_vert (A_AREA, A_CODMOD, A_NOME);
   END IF;
   RETURN s_valore;
EXCEPTION
   WHEN OTHERS
   THEN
      raise;
END F_CREA_VISTA_TIPODOC;
/

