CREATE OR REPLACE FUNCTION F_DOCUMENTO_IN_CATEGORIA(A_IDDOCUMENTO NUMBER, A_CATEGORIA VARCHAR2)
RETURN NUMBER
IS
A_RET NUMBER(4);
BEGIN
   SELECT DECODE(COUNT(*),0,0,1)
     INTO A_RET
     FROM MODELLI, DOCUMENTI, CATEGORIE_MODELLO
    WHERE MODELLI.ID_TIPODOC=DOCUMENTI.ID_TIPODOC
      AND DOCUMENTI.ID_DOCUMENTO=A_IDDOCUMENTO
      AND CATEGORIE_MODELLO.AREA=DOCUMENTI.AREA
      AND CATEGORIE_MODELLO.CODICE_MODELLO=MODELLI.CODICE_MODELLO
      AND CATEGORIA=A_CATEGORIA;
   RETURN A_RET;
END F_DOCUMENTO_IN_CATEGORIA;
/

