CREATE OR REPLACE FUNCTION F_ELIMINA_AREA(A_AREA VARCHAR2)
RETURN NUMBER IS
/*****************************************************************************************
   NAME:       F_ELIMINA_AREA
   PURPOSE:    SCOPO DELLA FUNZIONE E QUELLO DI ELIMINARE UN INTERA AREA:
   RETURN:     NESSUNA ELIMINAZIONE AREA/MODELLO ERRATO
               1 ELIMINA IL MODELLO
               2 NESSUNA ELIMINAZIONE PER PRESENZA DI DOCUMENTI:
                 (ELIMINARE PRIMA I DOCUMENTI)
   REVISIONS:
   VER   VER MODULIST.COMPATIBILITY DATE        AUTHOR           DESCRIPTION
   ----  -------------------------  ----------  ---------------  -------------------------
   1.0   TUTTE LE VERSIONI          06/11/2006  MARCO B          1. CREATED THIS FUNCTION.
*****************************************************************************************/
       RETVAL NUMBER(1) := 0;
       CURSOR C_MODELLI IS
         SELECT CODICE_MODELLO
           FROM MODELLI
          WHERE AREA = A_AREA
            AND CODICE_MODELLO_PADRE IS NULL;
BEGIN
  -- ELIMINO I MODELLI FIGLI
  FOR C0 IN C_MODELLI LOOP
      RETVAL := F_Elimina_Modello(A_AREA, C0.CODICE_MODELLO,'S');
      IF RETVAL = 2 THEN
         RETURN RETVAL;
      END IF;
  END LOOP;
  DELETE ALLEGATI_TEMP WHERE AREA = A_AREA;
  DELETE CONTROLLI_CARTELLE WHERE AREA = A_AREA;
  DELETE DATI WHERE AREA = A_AREA;
  DELETE DOMINI WHERE AREA = A_AREA;
  DELETE ETICHETTE WHERE AREA = A_AREA;
  DELETE FRASI_GLOSSARIO WHERE AREA = A_AREA;
  DELETE LIBRERIA_CONTROLLI WHERE AREA = A_AREA;
  DELETE RICHIESTE WHERE AREA = A_AREA;
  DELETE AREE WHERE AREA = A_AREA;
  RETURN RETVAL;
END F_ELIMINA_AREA;
/

