CREATE OR REPLACE FUNCTION F_Elimina_Dato(A_AREA VARCHAR2,A_MODELLO VARCHAR2, A_DATO VARCHAR2, A_NONINUSO VARCHAR2 DEFAULT 'S') RETURN NUMBER IS
TMPVAR NUMBER(1);
OK_OP VARCHAR2(1) := 'N';
/******************************************************************************
   NAME:       F_ELIMINA_DATO
   PURPOSE:    SCOPO DELLA FUNZIONE E QUELLO DI ELIMINARE EVENTUALI CAMPI IN
         PIU DAI MODELLI IN CUI COMPAIONO.
      OVVIAMENTE VERRANNO DROPPATI TUTTI I VALORI CORRISPONDENTI
      PRESENTI NELLA TABELLA VALORI.
   REVISIONS:
   VER        DATE        AUTHOR           DESCRIPTION
   ---------  ----------  ---------------  ------------------------------------
   1.0        07/02/2005          1. CREATED THIS FUNCTION.
   NOTES:
   AUTOMATICALLY AVAILABLE AUTO REPLACE KEYWORDS:
      OBJECT NAME:     F_ELIMINA_DATO
      SYSDATE:         07/02/2005
      DATE AND TIME:   07/02/2005, 10.40.07, AND 07/02/2005 10.40.07
      USERNAME:         (SET IN TOAD OPTIONS, PROCEDURE EDITOR)
      TABLE NAME:       (SET IN THE "NEW PL/SQL OBJECT" DIALOG)
******************************************************************************/
CURSOR C_1 IS
SELECT ID_CAMPO
  FROM DATI_MODELLO DM
 WHERE DM.AREA_DATO = A_AREA
   AND DM.DATO = A_DATO
   AND A_MODELLO IS NULL
 UNION ALL
SELECT ID_CAMPO
  FROM DATI_MODELLO DM
 WHERE DM.AREA_DATO = A_AREA
   AND DM.DATO = A_DATO
   AND DM.CODICE_MODELLO = A_MODELLO
   ;
BEGIN
FOR C1 IN C_1 LOOP
BEGIN
   TMPVAR := 0;
   IF (A_NONINUSO = 'S') THEN
   BEGIN
    SELECT 'N'
      INTO OK_OP
      FROM DUAL WHERE EXISTS (SELECT 1 FROM VALORI
                 WHERE ID_CAMPO = C1.ID_CAMPO
           AND NVL(DBMS_LOB.SUBSTR(VALORE_CLOB, 4000), NVL(TO_CHAR(VALORE_DATA, 'dd/mm/yyyy'),TO_CHAR(VALORE_NUMERO) )) IS NOT NULL
           );
   EXCEPTION
       WHEN NO_DATA_FOUND THEN
         OK_OP :=  'S';
   END;
   ELSE
       OK_OP := 'S';
   END IF;
   IF OK_OP = 'S' THEN
   BEGIN
     /* DROP DELLA TABELLA DEI VALORI */
     DELETE FROM VALORI WHERE ID_CAMPO = C1.ID_CAMPO;
  /* DROP DEI CAMPI DOCUMENTO */
  DELETE FROM CAMPI_DOCUMENTO WHERE ID_CAMPO = C1.ID_CAMPO;
    EXCEPTION
     WHEN OTHERS THEN
    ROLLBACK;
       RAISE_APPLICATION_ERROR('-20998',  SQLERRM);
 END;
 END IF;
END;
END LOOP;
BEGIN
/* DROP DEI DATI_MODELLO CHE POSSONO APPARTENERE ANCHE AI FIGLI*/
  DELETE FROM DATI_MODELLO WHERE DATO = A_DATO AND CODICE_MODELLO IN
      (SELECT CODICE_MODELLO FROM MODELLI WHERE AREA=A_AREA AND CODICE_MODELLO = A_MODELLO
   UNION
   SELECT CODICE_MODELLO FROM MODELLI WHERE AREA = A_AREA AND CODICE_MODELLO_PADRE = A_MODELLO);
 EXCEPTION
     WHEN OTHERS THEN
    ROLLBACK;
       RAISE_APPLICATION_ERROR('-20999',  SQLERRM);
END;
END F_Elimina_Dato;
/

