CREATE OR REPLACE FUNCTION F_ELIMINA_OGGETTOFILE(A_DOC NUMBER, A_OGGFILE NUMBER)
RETURN NUMBER
IS
TMPVAR NUMBER(1) := 0;
CURSOR C_1 IS
SELECT ID_OGGETTO_FILE
  FROM OGGETTI_FILE
 WHERE ID_DOCUMENTO = A_DOC
   AND A_OGGFILE  IS NULL
 UNION ALL
SELECT ID_OGGETTO_FILE
  FROM OGGETTI_FILE
 WHERE ID_OGGETTO_FILE = A_OGGFILE
   AND A_DOC   IS NULL
  UNION ALL
SELECT ID_OGGETTO_FILE
  FROM OGGETTI_FILE
 WHERE ID_OGGETTO_FILE_PADRE = A_OGGFILE
   AND A_DOC   IS NULL;
BEGIN
   FOR C1 IN C_1 LOOP
      BEGIN
       DELETE FROM OGGETTI_FILE
        WHERE ID_OGGETTO_FILE = C1.ID_OGGETTO_FILE;
       TMPVAR := 1;
      EXCEPTION
         WHEN OTHERS THEN
         ROLLBACK;
         RAISE_APPLICATION_ERROR('-20999',  SQLERRM);
      END;
   END LOOP;
   RETURN TMPVAR;
END F_ELIMINA_OGGETTOFILE;
/

