CREATE OR REPLACE FUNCTION F_ELIMINA_VISTE_TIPODOC RETURN VARCHAR2 IS
/*CANCELLA LE VISTE DEI TIPI DOCUMENTO NON PIU INUSO */
/* VERSIONE 1.0 CREATA IL 04/05/2005 DA ANDREA */
   S_ISTR  VARCHAR2(32767);
   CURSOR C_1  IS
      SELECT VIEW_NAME
      FROM USER_VIEWS
      WHERE VIEW_NAME LIKE 'GDM_%'
       AND VIEW_NAME NOT IN (SELECT 'GDM_'||ALIAS_VIEW FROM TIPI_DOCUMENTO
                               WHERE ALIAS_VIEW IS NOT NULL)
      --AND INSTR(TEXT, 'SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,') = 1
   ORDER BY 1 ASC;
BEGIN
    BEGIN
        FOR C1 IN C_1 LOOP
       BEGIN
            S_ISTR := 'DROP VIEW '||C1.VIEW_NAME ;
             SI4.SQL_EXECUTE( S_ISTR );
         EXCEPTION
           WHEN OTHERS THEN
         RETURN C1.VIEW_NAME;
       END;
       END LOOP;
    END;
    RETURN '1';
END  F_ELIMINA_VISTE_TIPODOC;
/

