CREATE OR REPLACE FUNCTION F_ELIMINA_CARTELLE (A_AREA VARCHAR2, A_CODICE_MODELLO VARCHAR2, A_USER VARCHAR2, A_CONTROLLA_USER VARCHAR2 DEFAULT 'S')
RETURN NUMBER IS
/*****************************************************************************************
 NAME:  F_ELIMINA_CARTELLE
 PURPOSE: ELIMINA LE CARTELLE DI AREA A_AREA E MODELLO A_CODICE_MODELLO
 E TUTTI GLI OGGETTI CONTENUTI FINO ALLE FOGLIE DELL'ALBERO
 RETURN: 1 SE ELIMINA LA CARTELLA
 0 ALTRIMENTI
 REVISIONS:
 VER VER DMSERVER COMPATIBILITY DATE AUTHOR DESCRIPTION
 ---- ------------------------- ---------- --------------- -------------------------
 1.0 TUTTE LE VERSIONI 09/02/2007 MANNELLA G. 1. CREATED THIS FUNCTION.
*****************************************************************************************/
 TMPVAR NUMBER(1) := 0;
 CURSOR C_FOLDERLIST IS
 SELECT ID_CARTELLA
 FROM CARTELLE C, DOCUMENTI D, MODELLI M
 WHERE C.ID_DOCUMENTO_PROFILO = D.ID_DOCUMENTO
 AND D.ID_TIPODOC = M.ID_TIPODOC
 AND D.AREA=A_AREA AND CODICE_MODELLO=A_CODICE_MODELLO
 AND ID_CARTELLA>0
 ORDER BY 1 DESC;
 CONTATORE NUMBER := 0;
BEGIN
 TMPVAR:=1;
 FOR CFOLDERLIST IN C_FOLDERLIST LOOP
 TMPVAR:=F_ELIMINA_CARTELLA(CFOLDERLIST.ID_CARTELLA,A_USER,A_CONTROLLA_USER);
 CONTATORE:=CONTATORE+1;
 IF CONTATORE = 100 THEN
 COMMIT;
 CONTATORE := 0;
 END IF;
 END LOOP;
 COMMIT;
 RETURN TMPVAR;
END F_ELIMINA_CARTELLE;
/

