CREATE OR REPLACE FUNCTION F_Elimina_Cartella(A_IDCARTELLA NUMBER,A_USER VARCHAR2, A_CONTROLLA_UTENTE VARCHAR2 DEFAULT 'S')
RETURN NUMBER IS
BEGIN
 RETURN F_Elimina_Cartella_LF(A_IDCARTELLA,A_USER,A_CONTROLLA_UTENTE,'F');
 EXCEPTION
   WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR('-20999','PROBLEMI IN ELIMINA CARTELLA FISICA'
                                ||') DESCRIZIONE ERRORE: '||SQLERRM);
 RETURN 0;
END F_Elimina_Cartella;
/

