CREATE OR REPLACE FUNCTION F_FULL_TEXT(A_ID_DOCUMENTO NUMBER)
RETURN VARCHAR2 IS
RETVAL      VARCHAR2(4000);
P_AREA              VARCHAR2(200);
P_CM                VARCHAR2(200);
NOMETABELLA         VARCHAR2(30);
C_CLOB              CLOB;
F_TEXT              CLOB;
VALORE              VARCHAR2(4000);
D_NEW_TESTO         VARCHAR2(4000);
D_CURSOR            INTEGER;
D_ROWS_PROCESSED    INTEGER;
CURSOR C_CAMPI_N(V_AREA VARCHAR2, V_CM VARCHAR2)
IS
SELECT DM.DATO DATO, D.TIPO TIPO
 FROM DATI_MODELLO DM,
      DATI D
WHERE DM.AREA = V_AREA
  AND DM.CODICE_MODELLO = V_CM
  AND D.AREA = DM.AREA_DATO
  AND D.DATO = DM.DATO
  AND D.LUNGHEZZA <= 4000
  AND DM.IN_USO = 'Y';
CURSOR C_CAMPI_CLOB(V_AREA VARCHAR2, V_CM VARCHAR2)
IS
SELECT DM.DATO DATO
 FROM DATI_MODELLO DM,
      DATI D
WHERE DM.AREA = V_AREA
  AND DM.CODICE_MODELLO = V_CM
  AND D.AREA = DM.AREA_DATO
  AND D.DATO = DM.DATO
  AND D.LUNGHEZZA > 4000
  AND DM.IN_USO = 'Y';
BEGIN
  BEGIN
    RETVAL := '';
    F_TEXT := '';
    SELECT M.AREA, M.CODICE_MODELLO
      INTO P_AREA, P_CM
      FROM DOCUMENTI D,
           MODELLI M
     WHERE D.ID_TIPODOC = M.ID_TIPODOC
       AND D.ID_DOCUMENTO = A_ID_DOCUMENTO;
   NOMETABELLA := F_NOME_TABELLA(P_AREA, P_CM);
    FOR V_CAMPI_N IN C_CAMPI_N(P_AREA, P_CM ) LOOP
        VALORE := F_VALORE_CAMPO(A_ID_DOCUMENTO,V_CAMPI_N.DATO);
        IF (NVL(VALORE,'-') <> '-') THEN
            IF (NVL(F_TEXT,'-') <> '-') THEN
                F_TEXT := F_TEXT||CHR(13)||VALORE;
            ELSE
                 F_TEXT := VALORE;
            END IF;
        END IF;
    END LOOP;
    FOR V_CAMPI_CLOB IN C_CAMPI_CLOB(P_AREA, P_CM ) LOOP
        C_CLOB := F_VALORE_CAMPO_CLOB(A_ID_DOCUMENTO,V_CAMPI_CLOB.DATO);
        F_TEXT := F_TEXT||CHR(13)||C_CLOB;
    END LOOP;
    D_NEW_TESTO := 'UPDATE '||NOMETABELLA||' SET FULL_TEXT = :PAR WHERE ID_DOCUMENTO = '||A_ID_DOCUMENTO;
    D_CURSOR := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE( D_CURSOR, D_NEW_TESTO, DBMS_SQL.NATIVE );
    DBMS_SQL.BIND_VARIABLE(D_CURSOR,':PAR',F_TEXT);
    D_ROWS_PROCESSED := DBMS_SQL.EXECUTE( D_CURSOR );
    DBMS_SQL.CLOSE_CURSOR( D_CURSOR );
   EXCEPTION
     WHEN OTHERS THEN
       RETVAL := SUBSTR(SQLERRM,1,4000);
  END;
  RETURN RETVAL;
END F_FULL_TEXT;
/

