CREATE OR REPLACE FUNCTION F_FULL_TEXT_EXECUTEUPDATE(STRSELECT VARCHAR2,A_ID_DOCUMENTO NUMBER,A_NOME_TABELLA VARCHAR2)
RETURN VARCHAR2 IS
RETVAL              VARCHAR2(4000);
D_NEW_TESTO         VARCHAR2(32000);
D_CURSOR            INTEGER;
D_ROWS_PROCESSED    INTEGER;
BEGIN
RETVAL    := ' ';
D_NEW_TESTO := 'UPDATE '||A_NOME_TABELLA||' SET FULL_TEXT = ('||STRSELECT||') WHERE ID_DOCUMENTO = '||A_ID_DOCUMENTO;
D_CURSOR := DBMS_SQL.OPEN_CURSOR;
DBMS_SQL.PARSE( D_CURSOR, D_NEW_TESTO, DBMS_SQL.NATIVE );
D_ROWS_PROCESSED := DBMS_SQL.EXECUTE( D_CURSOR );
DBMS_SQL.CLOSE_CURSOR( D_CURSOR );
RETURN RETVAL;
EXCEPTION
  WHEN OTHERS THEN
       RETURN SUBSTR(SQLERRM,1,4000);
END F_FULL_TEXT_EXECUTEUPDATE;
/

