CREATE OR REPLACE FUNCTION F_FULL_TEXT_HORIZ(A_ID_DOCUMENTO NUMBER,A_NOME_TABELLA VARCHAR2)
RETURN VARCHAR2 IS
RETVAL     VARCHAR2(4000);
STRSELECT  VARCHAR2(32000);
APICE      VARCHAR2(1);
STRFORMAT  VARCHAR2(20);
CAMPOUNION VARCHAR2(500);
VAL        VARCHAR2(32000);
F_TEXT     CLOB;
CONTA      NUMBER(3);
D_NEW_TESTO         VARCHAR2(4000);
D_CURSOR            INTEGER;
D_ROWS_PROCESSED    INTEGER;
TYPE CDYN_HORIZSELECT IS REF CURSOR;
CV CDYN_HORIZSELECT;
CURSOR C_CAMPI_TABELLA IS
       SELECT COLUMN_NAME, DATA_TYPE
       FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME=A_NOME_TABELLA AND COLUMN_NAME <> 'FULL_TEXT' AND UPPER(COLUMN_NAME)<> '$ACTIONKEY' AND COLUMN_NAME <> 'ID_DOCUMENTO';
BEGIN
RETVAL    := '';
F_TEXT    := '';
STRSELECT := '';
APICE     := '''';
D_NEW_TESTO := 'UPDATE '||A_NOME_TABELLA||' SET FULL_TEXT = EMPTY_CLOB() WHERE ID_DOCUMENTO = '||A_ID_DOCUMENTO;
D_CURSOR := DBMS_SQL.OPEN_CURSOR;
DBMS_SQL.PARSE( D_CURSOR, D_NEW_TESTO, DBMS_SQL.NATIVE );
D_ROWS_PROCESSED := DBMS_SQL.EXECUTE( D_CURSOR );
DBMS_SQL.CLOSE_CURSOR( D_CURSOR );
FOR V_CAMPI IN C_CAMPI_TABELLA LOOP
    IF V_CAMPI.DATA_TYPE='DATE' THEN
       STRFORMAT:=',''DD/MM/YYYY''';
    ELSE
       STRFORMAT:='';
    END IF;
    IF V_CAMPI.DATA_TYPE='CLOB' THEN
      CAMPOUNION:=V_CAMPI.COLUMN_NAME;
    ELSE
       CAMPOUNION:='TO_CHAR('||V_CAMPI.COLUMN_NAME||STRFORMAT||')';
    END IF;
        STRSELECT:=STRSELECT||CAMPOUNION;
    IF length(STRSELECT)>30000 THEN
        STRSELECT:= 'SELECT FULL_TEXT||'||STRSELECT||' VAL'||' FROM '||A_NOME_TABELLA||' WHERE ID_DOCUMENTO='||A_ID_DOCUMENTO;
        RETVAL:=F_FULL_TEXT_EXECUTEUPDATE(STRSELECT,A_ID_DOCUMENTO,A_NOME_TABELLA);
        IF RETVAL<>' ' THEN
           RAISE_APPLICATION_ERROR(-20999,RETVAL);
        END IF;
        STRSELECT:=' ';
        RETVAL:='';
    END IF;
    IF (NOT C_CAMPI_TABELLA%NOTFOUND) THEN
        IF STRSELECT<>' ' THEN
            STRSELECT:=STRSELECT||'||chr(13)||chr(10)||';
        END IF;
    END IF;
END LOOP;
IF STRSELECT<> ' ' THEN
    STRSELECT:=substr(STRSELECT,1,length(STRSELECT)-length('||'));
    STRSELECT:= 'SELECT FULL_TEXT||'||STRSELECT||' VAL'||' FROM '||A_NOME_TABELLA||' WHERE ID_DOCUMENTO='||A_ID_DOCUMENTO;
    RETVAL:=F_FULL_TEXT_EXECUTEUPDATE(STRSELECT,A_ID_DOCUMENTO,A_NOME_TABELLA);
    IF RETVAL=' ' THEN
       RETURN '';
    ELSE
       RAISE_APPLICATION_ERROR(-20999,RETVAL);
    END IF;
END IF;
EXCEPTION
  WHEN OTHERS THEN
       RETURN SUBSTR(SQLERRM,1,4000);
END F_FULL_TEXT_HORIZ;
/

