CREATE OR REPLACE FUNCTION F_GET_MAXDIM_ATTACH(P_AREA VARCHAR2, P_CODICE_MODELLO VARCHAR2)
RETURN VARCHAR2 IS
   N_MAX_DIM                      VARCHAR2(100);
   N_DIM_MAX_ALL_BYTE_PAR         PARAMETRI.VALORE%TYPE;
   N_DIM_MAX_ALL_BYTE_BLOCC_PAR   PARAMETRI.VALORE%TYPE;
 BEGIN
 BEGIN
    SELECT VALORE
      INTO N_DIM_MAX_ALL_BYTE_PAR
      FROM PARAMETRI
     WHERE CODICE='DIM_MAX_ALL_BYTE'
       AND TIPO_MODELLO='@DMSERVER@';
 EXCEPTION WHEN NO_DATA_FOUND THEN
    N_DIM_MAX_ALL_BYTE_PAR:=NULL;
 END;
 BEGIN
    SELECT VALORE
      INTO N_DIM_MAX_ALL_BYTE_BLOCC_PAR
      FROM PARAMETRI
     WHERE CODICE='DIM_MAX_ALL_BYTE_ALT'
       AND TIPO_MODELLO='@DMSERVER@';
  EXCEPTION WHEN NO_DATA_FOUND THEN
    N_DIM_MAX_ALL_BYTE_BLOCC_PAR:=NULL;
  END;
  SELECT DECODE( MODELLI.DIM_MAX_ALL_BYTE , NULL,
                  DECODE( AREE.DIM_MAX_ALL_BYTE, NULL, DECODE(N_DIM_MAX_ALL_BYTE_PAR,NULL,NULL, N_DIM_MAX_ALL_BYTE_PAR||'@'||NVL(N_DIM_MAX_ALL_BYTE_BLOCC_PAR,'Y')) ,AREE.DIM_MAX_ALL_BYTE ||'@'|| AREE.DIM_MAX_ALL_BYTE_BLOCCANTE ),
                  MODELLI.DIM_MAX_ALL_BYTE ||'@'|| MODELLI.DIM_MAX_ALL_BYTE_BLOCCANTE )
   INTO N_MAX_DIM
   FROM AREE, MODELLI
   WHERE AREE.AREA=P_AREA
     AND MODELLI.AREA=AREE.AREA
     AND MODELLI.CODICE_MODELLO=P_CODICE_MODELLO;
   RETURN N_MAX_DIM;
 END  F_GET_MAXDIM_ATTACH;
/

