CREATE OR REPLACE FUNCTION F_GETPATH_FILE_FS(P_ID_DOCUMENTO NUMBER, P_IDOGGETTO_FILE NUMBER, P_ONLYDIR NUMBER DEFAULT 0, P_IDLOG NUMBER DEFAULT 0) RETURN VARCHAR2
IS
A_ID_DOCUMENTO  DOCUMENTI.ID_DOCUMENTO%TYPE;
A_DIRAREA_NAME   VARCHAR2(30);
A_CARTELLA           VARCHAR2(1000);
A_PATH                  VARCHAR2(1000);
A_PATH_ROOT_IN_OGFI  VARCHAR2(1000);
A_PATH_ROOT_IN_AREE  VARCHAR2(1000);
BEGIN
            IF P_IDLOG=0 THEN
               select F_GETDIRECTORY_AREA_NAME(DOCUMENTI.ID_DOCUMENTO),
                    AREE.ACRONIMO||'/'||   TIPI_DOCUMENTO.ACRONIMO_MODELLO || '/' || to_char(trunc(DOCUMENTI.ID_DOCUMENTO/1000)) || '/' || DOCUMENTI.ID_DOCUMENTO || decode(P_ONLYDIR,1,'', '/' || P_IDOGGETTO_FILE),
                       OGGETTI_FILE.PATH_FILE_ROOT_ORACLE,AREE.PATH_FILE_ORACLE
                 into A_DIRAREA_NAME,A_CARTELLA, A_PATH_ROOT_IN_OGFI,A_PATH_ROOT_IN_AREE
              from TIPI_DOCUMENTO, AREE, DOCUMENTI, OGGETTI_FILE
              WHERE DOCUMENTI.ID_DOCUMENTO=P_ID_DOCUMENTO
                   AND DOCUMENTI.AREA=AREE.AREA
                   AND DOCUMENTI.ID_TIPODOC=TIPI_DOCUMENTO.ID_TIPODOC
                   AND OGGETTI_FILE.ID_OGGETTO_FILE =P_IDOGGETTO_FILE ;
           ELSE
                select F_GETDIRECTORY_AREA_NAME(DOCUMENTI.ID_DOCUMENTO),
                    AREE.ACRONIMO||'/'||   TIPI_DOCUMENTO.ACRONIMO_MODELLO || '/' || to_char(trunc(DOCUMENTI.ID_DOCUMENTO/1000)) || '/' || DOCUMENTI.ID_DOCUMENTO ||  '/LOG_' || TO_CHAR(OGGETTI_FILE_LOG.ID_LOG) || decode(P_ONLYDIR,1,'', '/' || P_IDOGGETTO_FILE),
                       OGGETTI_FILE_LOG.PATH_FILE_ROOT_ORACLE,AREE.PATH_FILE_ORACLE
                 into A_DIRAREA_NAME,A_CARTELLA, A_PATH_ROOT_IN_OGFI,A_PATH_ROOT_IN_AREE
              from TIPI_DOCUMENTO, AREE, DOCUMENTI, OGGETTI_FILE_LOG
              WHERE DOCUMENTI.ID_DOCUMENTO=P_ID_DOCUMENTO
                   AND DOCUMENTI.AREA=AREE.AREA
                   AND DOCUMENTI.ID_TIPODOC=TIPI_DOCUMENTO.ID_TIPODOC
                   AND OGGETTI_FILE_LOG.ID_LOG =P_IDLOG  AND OGGETTI_FILE_LOG.ID_OGGETTO_FILE=P_IDOGGETTO_FILE ;
           END IF;

            IF A_PATH_ROOT_IN_OGFI IS NULL THEN
                RETURN A_PATH_ROOT_IN_AREE||'/'||A_CARTELLA;
            ELSE
               RETURN A_PATH_ROOT_IN_OGFI||'/'||A_CARTELLA;
            END IF;

END;
/

