CREATE OR REPLACE FUNCTION F_IDCARTELLA_IDVIEW(A_ID_VIEW_CARTELLA NUMBER)
RETURN VARCHAR2 IS
/*  BY ANDREA*/
   IDC VARCHAR2(20);
 BEGIN
   BEGIN
    SELECT ID_CARTELLA
      INTO IDC
      FROM VIEW_CARTELLA
     WHERE ID_VIEWCARTELLA = A_ID_VIEW_CARTELLA
      ;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN NULL;
   END;
   RETURN IDC;
 END F_IDCARTELLA_IDVIEW ;
/

