CREATE OR REPLACE FUNCTION F_IDDOC_FROM_CM_AREA_CR(A_CM VARCHAR,A_AREA VARCHAR,A_CR VARCHAR)
RETURN NUMBER IS
/*****************************************************************************************
   NAME:       F_IDDOC_FROM_CM_AREA_CR
   PURPOSE:    SCOPO DELLA FUNZIONE E QUELLO DI RESTITUIRE IDDOCUMENTO A PARTIRE DALLA TERNA (CM,AREA,CR)
   RETURN:     IDDOCUMENTO ALTRIMENTI IN CASO DI ERRORE -1
   REVISIONS:
   VER   VER MODULIST.COMPATIBILITY DATE        AUTHOR           DESCRIPTION
   ----  -------------------------  ----------  ---------------  -------------------------
   1.0   TUTTE LE VERSIONI          07/03/2008  DANIELA S         1. CREATED THIS FUNCTION.
*****************************************************************************************/
   IDDOC DOCUMENTI.ID_DOCUMENTO%TYPE;
   IDTIPODOC DOCUMENTI.ID_TIPODOC%TYPE;
   CM_PADRE MODELLI.CODICE_MODELLO%TYPE;
 BEGIN

   BEGIN

    IDDOC:=-1;
     /* RECUPERO ID_TIPODOC */
    IDTIPODOC:=NULL;

    SELECT id_tipodoc
    INTO IDTIPODOC
    FROM modelli M
    WHERE M.AREA=A_AREA and M.CODICE_MODELLO=A_CM;

    /* SE ID_TIPODOC è NULLO RECUPERO QUELLO DEL MODELLO PADRE */
    IF IDTIPODOC IS NULL THEN

        SELECT M.CODICE_MODELLO_PADRE
        INTO CM_PADRE
        FROM MODELLI M
        WHERE M.AREA=A_AREA AND M.CODICE_MODELLO=A_CM;

        IF CM_PADRE IS NULL THEN
           RETURN -2;
        ELSE
          SELECT ID_TIPODOC
          INTO IDTIPODOC
          FROM MODELLI M
          WHERE M.AREA=A_AREA AND M.CODICE_MODELLO=CM_PADRE;
        END IF;

    END IF;

    SELECT D.ID_DOCUMENTO
    INTO IDDOC
    FROM DOCUMENTI D
    WHERE D.AREA=A_AREA AND D.CODICE_RICHIESTA=A_CR AND D.ID_TIPODOC=IDTIPODOC;

    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN -1;
   END;
   RETURN IDDOC;
 END F_IDDOC_FROM_CM_AREA_CR;
/

