CREATE OR REPLACE FUNCTION F_IDDOC_FROM_CARTELLA(A_CARTELLA NUMBER)
RETURN NUMBER IS
/*  BY MANNY*/
   IDDOC NUMBER;
 BEGIN
   BEGIN
   SELECT ID_DOCUMENTO_PROFILO
   INTO IDDOC
   FROM CARTELLE
   WHERE ID_CARTELLA=A_CARTELLA;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN -1;
   END;
   RETURN IDDOC;
 END F_IDDOC_FROM_CARTELLA ;
/

