CREATE OR REPLACE FUNCTION F_IDDOC_FROM_QUERY(A_QUERY NUMBER)
RETURN NUMBER IS
/*  BY MANNY*/
   IDDOC NUMBER;
 BEGIN
   BEGIN
   SELECT ID_DOCUMENTO_PROFILO
   INTO IDDOC
   FROM QUERY
   WHERE ID_QUERY=A_QUERY;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN -1;
   END;
   RETURN IDDOC;
 END F_IDDOC_FROM_QUERY ;
/

