CREATE OR REPLACE FUNCTION F_LIBRERIA(A_LIBRERIA NUMBER)
RETURN VARCHAR2 IS
/*  BY ANDREA*/
   DESCRIZIONE VARCHAR2(200);
 BEGIN
   BEGIN
    SELECT LIBRERIA
      INTO DESCRIZIONE
      FROM LIBRERIE
     WHERE ID_LIBRERIA = A_LIBRERIA;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      RETURN NULL;
   END;
   RETURN DESCRIZIONE;
 END F_LIBRERIA ;
/

