CREATE OR REPLACE FUNCTION F_NAMEFILE_EXT (P_NAME IN VARCHAR2)
RETURN VARCHAR2 IS
P_EXT  NUMBER(10) := 15;
NAME_RETURN VARCHAR(2000);
BEGIN
    IF LENGTH(P_NAME) > P_EXT THEN
      NAME_RETURN:=''||SUBSTR(SUBSTR(P_NAME,1,INSTR(P_NAME,'.')-1),1,15)||'[...]'||SUBSTR(P_NAME,-4,LENGTH(P_NAME));
   ELSE
      NAME_RETURN:=''||P_NAME;
   END IF;
   RETURN NAME_RETURN;
END F_NAMEFILE_EXT;
/

