CREATE OR REPLACE FUNCTION F_NOMINATIVO_UTENTE
( P_UTENTE VARCHAR2)
RETURN VARCHAR2
IS
RETVAL VARCHAR2(200);
BEGIN
         SELECT NOMINATIVO
           INTO RETVAL
           FROM AD4_UTENTI
          WHERE UTENTE = P_UTENTE
            AND TIPO_UTENTE = 'U';
   RETURN RETVAL;
   EXCEPTION
    WHEN OTHERS THEN
         RETURN P_UTENTE;
END;
/

