CREATE OR REPLACE FUNCTION F_NOME_INDICE(P_AREA VARCHAR2, P_CODICE_MODELLO VARCHAR2, P_DATO VARCHAR2)
RETURN VARCHAR2 IS
NOMEINDICE         VARCHAR2(30);
NOMETABELLA        VARCHAR2(30);
BEGIN
  BEGIN
    NOMETABELLA := F_NOME_TABELLA(P_AREA, P_CODICE_MODELLO);
    IF NOMETABELLA = '' THEN
        RETURN '';
    END IF;
    SELECT U.INDEX_NAME
      INTO NOMEINDICE
      FROM USER_IND_COLUMNS U,
                DATI D
     WHERE U.COLUMN_NAME = P_DATO
       AND U.TABLE_NAME = NOMETABELLA
       AND D.DATO = U.COLUMN_NAME
       AND D.AREA = P_AREA
       AND U.INDEX_NAME LIKE '%'||NVL(D.ACRONIMO_DATO,'*')||'%';
   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NOMEINDICE := '';
     WHEN OTHERS THEN
       return SUBSTR(SQLERRM,1,4000);
  END;
  RETURN NOMEINDICE;
END F_NOME_INDICE;
/

