CREATE OR REPLACE FUNCTION F_PATH_COLLEGAMENTO(A_COLLEGAMENTO NUMBER,A_CARTELLA VARCHAR2,A_TYPE VARCHAR2,A_UTENTE VARCHAR2)
RETURN VARCHAR2 IS
/*****************************************************************************************
   NAME:       F_PATH_COLLEGAMENTO
   PURPOSE:    RESTITUISCE IL PATH LOGICO ALLA CARTELLA A_CARTELLA
               RISPETTO AL COLLEGAMENTO A_COLLEGAMENTO
               IL PARAMETRO A_TYPE PUO' PRENDERE DUE VALORI:
                   W: PERCORSO IN HTML CON ANCHORE CONTENENTI LINK ALLE CARTELLE
                      DEL PATH
                   I: PERCORSO SEMPLICE
   RETURN:     PATH LOGICO ALLA CARTELLA A_CARTELLA
               RISPETTO AL COLLEGAMENTO A_COLLEGAMENTO
   REVISIONS:
   VER   VER DMSERVER.COMPATIBILITY DATE        AUTHOR           DESCRIPTION
   ----  -------------------------  ----------  ---------------  -------------------------
   1.0   TUTTE LE VERSIONI          30/05/2006  MANNELLA G.      1. CREATED THIS FUNCTION.
*****************************************************************************************/
       DESCR                           VARCHAR2(2000) := NULL;
       ID_CARTELLA_COLLEGAMENTO        CARTELLE.ID_CARTELLA%TYPE;
       ID_CARTELLA_PADRE_COLLEGAMENTO  CARTELLE.ID_CARTELLA%TYPE;
BEGIN
  SELECT ID_CARTELLA,ID_CARTELLA_COLLEGATA
    INTO ID_CARTELLA_PADRE_COLLEGAMENTO,ID_CARTELLA_COLLEGAMENTO
    FROM COLLEGAMENTI
   WHERE ID_COLLEGAMENTO=A_COLLEGAMENTO;
  DESCR:=F_PATH_FOLDER(ID_CARTELLA_PADRE_COLLEGAMENTO,A_TYPE,A_UTENTE);
  IF A_TYPE='I' THEN
     DESCR:=DESCR||'@'||F_PATH_SOTTOALBERO(ID_CARTELLA_COLLEGAMENTO,A_CARTELLA,A_COLLEGAMENTO,A_TYPE);
  ELSE
     DESCR:=DESCR||'<font color="red">&nbsp;::&nbsp;'||F_PATH_SOTTOALBERO(ID_CARTELLA_COLLEGAMENTO,A_CARTELLA,A_COLLEGAMENTO,A_TYPE)||'</font>';
  END IF;
  IF LENGTH(DESCR)<=475 THEN
    RETURN DESCR;
  ELSE
   return descr;
   -- RETURN '...'||SUBSTR(SUBSTR(DESCR,-475,length(DESCR)),instr(SUBSTR(DESCR,-475,length(DESCR)),'<A',1),475);
   -- RETURN SUBSTR(SUBSTR(DESCR,1,475),1,instr(SUBSTR(DESCR,1,475),'</A>',-1)-1)||'...';
  END IF;
END F_PATH_COLLEGAMENTO;
/

