CREATE OR REPLACE FUNCTION F_SPOSTA_DOCUMENTI (A_MODELLO_OLD VARCHAR2, A_AREA_OLD VARCHAR2, A_MODELLO_NEW VARCHAR2, A_AREA_NEW VARCHAR2) RETURN VARCHAR2 IS
/******************************************************************************
   NAME:        F_SPOSTA_DOCUMENTO
   PURPOSE:    SCOPO DELLA FUNZIONE E QUELLO DI SPOSTARE TUTTI I DOCUMENTI DI UN MODELLO DA UN AREA AD UN ALTRA:
   RETURN:    STRINGA VUOTA SE I DOCUMENTI SONO STATI SPOSTATI, ALTRIMENTI LA SEGNALAZIONE DI ERRORE
   REVISIONS:
   VER        DATE        AUTHOR           DESCRIPTION
   ---------  ----------  ---------------  ------------------------------------
   1.0        04/07/2007  MARCO B          1. CREATED THIS FUNCTION.
   NOTES:
   AUTOMATICALLY AVAILABLE AUTO REPLACE KEYWORDS:
      OBJECT NAME:      F_SPOSTA_DOCUMENTI
      DATE AND TIME:   01/09/2005
      USERNAME:         (SET IN TOAD OPTIONS, PROCEDURE EDITOR)
      TABLE NAME:       (SET IN THE "NEW PL/SQL OBJECT" DIALOG)
******************************************************************************/
D_RETURN VARCHAR2(1000);
D_CONTA  NUMBER(10) :=0;
    BEGIN
    FOR C_CUR IN (
    SELECT DOCU.ID_DOCUMENTO
       FROM DOCUMENTI DOCU,
            MODELLI M
      WHERE
        DOCU.ID_TIPODOC = M.ID_TIPODOC
        AND M.CODICE_MODELLO_PADRE IS NULL
        AND M.AREA = A_AREA_OLD
        AND M.CODICE_MODELLO = A_MODELLO_OLD
        --AND ID_DOCUMENTO IN (1145302, 1145303)
        ) LOOP
        D_CONTA := D_CONTA+1;
        D_RETURN := F_SPOSTA_DOCUMENTO(C_CUR.ID_DOCUMENTO, A_AREA_NEW);
        IF MOD(D_CONTA,1000) = 0 THEN
           COMMIT;
        END IF;
    END LOOP;
    RETURN D_RETURN;
    END F_SPOSTA_DOCUMENTI;
/

