CREATE OR REPLACE FUNCTION F_STATO_DOCUMENTO(IDDOC NUMBER)
RETURN VARCHAR2 IS
   V_STATO VARCHAR2(2);
 BEGIN
    SELECT NVL(STATO_DOCUMENTO,'BO')
      INTO V_STATO
      FROM DOCUMENTI
     WHERE ID_DOCUMENTO = IDDOC;
    RETURN V_STATO;
    EXCEPTION
    WHEN OTHERS THEN
       RETURN NULL;
 END  F_STATO_DOCUMENTO;
/

