CREATE OR REPLACE FUNCTION F_VALORE_CAMPO_CLOB(P_DOC VARCHAR2,  P_CAMPO           VARCHAR2)
RETURN CLOB IS
/*  BY MMA*/
   S_VALORE     CLOB;
   N_CAMPO         NUMBER(20);
   N_TIPODOC     NUMBER(10);
 BEGIN
        SELECT ID_TIPODOC
          INTO N_TIPODOC
          FROM DOCUMENTI
         WHERE ID_DOCUMENTO = P_DOC;
        SELECT C.ID_CAMPO
          INTO N_CAMPO
          FROM CAMPI_DOCUMENTO C
         WHERE C.ID_TIPODOC = N_TIPODOC
           AND C.NOME = P_CAMPO;
        SELECT VALORE_CLOB
          INTO S_VALORE
          FROM VALORI
         WHERE ID_DOCUMENTO = P_DOC
           AND ID_CAMPO = N_CAMPO;
       RETURN S_VALORE;
    EXCEPTION
      WHEN OTHERS THEN
       RETURN NULL;
 END  F_VALORE_CAMPO_CLOB ;
/

