CREATE OR REPLACE FUNCTION F_VALORE_CAMPO (P_DOC VARCHAR2, P_CAMPO VARCHAR2)
   RETURN VARCHAR2
IS
   S_VALORE   VARCHAR2(4000);
BEGIN
   S_VALORE := F_VALORE_CAMPO_ORIZ(P_DOC, P_CAMPO);
   RETURN S_VALORE;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN f_valore_campo_ver(p_doc, p_campo);
END F_VALORE_CAMPO;
/

