CREATE OR REPLACE FUNCTION F_VALORE_CAMPO_MULTIPLA(P_DOC VARCHAR2,P_CAMPO VARCHAR2)
/*****************************************************************************************
   NAME:       F_VALORE_CAMPO_MULTIPLA
   PURPOSE:    RESTITUISCE IL VALORE DEL CAMPO P_CAMPO PER IL DOCUMENTO P_DOC.
               IL P_CAMPO PUO' ESSERE PASSATO NELLA FORMA:
                    NOME_CAMPO#NOME_CAMPO_ALTERNATIVO#....#....
               SE NON SI E' SICURI DEL NOME DEL CAMPO PER IL DOCUMENTO.
               RICORSIVAMENTE VERRA' TENTATA LA F_VALORE_CAMPO SU OGNI
               ITEM DELLA STRINGA.
   RETURN:     VALORE DEL CAMPO PER IL DOCUMENTO
   REVISIONS:
   VER   VER DMSERVER.COMPATIBILITY DATE        AUTHOR           DESCRIPTION
   ----  -------------------------  ----------  ---------------  -------------------------
   1.0   TUTTE LE VERSIONI          13/07/2007  MANNELLA G.      1. CREATED THIS FUNCTION.
*****************************************************************************************/
RETURN VARCHAR2 IS
      D_VALORE_ATTUALE  VARCHAR2(4000);
    D_VALORE_RESTANTE VARCHAR2(4000);
    D_VALORE          VARCHAR2(4000);
 BEGIN
    IF INSTR(P_CAMPO,'#')=0 THEN
        D_VALORE:=F_VALORE_CAMPO(P_DOC,P_CAMPO);
    ELSE
        D_VALORE_RESTANTE:=P_CAMPO;
        LOOP
           D_VALORE_ATTUALE:=SUBSTR(D_VALORE_RESTANTE,1,INSTR(D_VALORE_RESTANTE,'#')-1);
           D_VALORE_RESTANTE:=SUBSTR(D_VALORE_RESTANTE,INSTR(D_VALORE_RESTANTE,'#')+1,LENGTH(D_VALORE_RESTANTE));
           D_VALORE:=F_VALORE_CAMPO(P_DOC,D_VALORE_ATTUALE);
            IF LENGTH(NVL(D_VALORE,''))>0 THEN
              RETURN D_VALORE;
           END IF;
           IF INSTR(D_VALORE_RESTANTE,'#')=0 THEN
              RETURN F_VALORE_CAMPO(P_DOC,D_VALORE_RESTANTE);
           END IF;
        END LOOP;
    END IF;
    RETURN D_VALORE;
   EXCEPTION
     WHEN OTHERS THEN
      RETURN NULL;
 END  F_VALORE_CAMPO_MULTIPLA ;
/

