CREATE OR REPLACE FUNCTION F_VALORE_CAMPO_VER_TRASCO (
   P_DOC     VARCHAR2,
   P_CAMPO   VARCHAR2
)
   RETURN VARCHAR2
IS
   S_VALORE    VARCHAR2 (4000);
   N_CAMPO     NUMBER (20);
   N_TIPODOC   NUMBER (10);
BEGIN
   SELECT ID_TIPODOC
     INTO N_TIPODOC
     FROM DOCUMENTI
    WHERE ID_DOCUMENTO = P_DOC;
   SELECT C.ID_CAMPO
     INTO N_CAMPO
     FROM CAMPI_DOCUMENTO C
    WHERE C.ID_TIPODOC = N_TIPODOC AND C.NOME = P_CAMPO;
   SELECT DECODE(DATI.TIPO,'S',VALORE_STRINGA,
                           'D',TO_CHAR (VALORE_DATA,NVL (REPLACE (FORMATO_DATA, 'hh:', 'hh24:'),'dd/mm/yyyy')),
                           'N',TO_CHAR (VALORE_NUMERO)
                )
     INTO S_VALORE
     FROM VALORI, CAMPI_DOCUMENTO, DATI_MODELLO, DATI
    WHERE ID_DOCUMENTO = P_DOC
      AND VALORI.ID_CAMPO = N_CAMPO
      AND CAMPI_DOCUMENTO.ID_CAMPO = VALORI.ID_CAMPO
      AND CAMPI_DOCUMENTO.ID_CAMPO = DATI_MODELLO.ID_CAMPO
      AND DATI_MODELLO.AREA_DATO = DATI.AREA
      AND DATI_MODELLO.DATO = DATI.DATO;
   RETURN S_VALORE;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN NULL;
END F_VALORE_CAMPO_VER_TRASCO;
/

