CREATE OR REPLACE FUNCTION F_VERIFICA
( P_TIPO_OGGETTO IN VARCHAR2
, P_OGGETTO IN VARCHAR2
, P_TIPO_ABILITAZIONE IN VARCHAR2
, P_UTENTE IN VARCHAR2
, P_RUOLO IN VARCHAR2 DEFAULT NULL
, P_DATA IN VARCHAR2 DEFAULT TO_CHAR(SYSDATE,'dd/mm/yyyy'))
RETURN NUMBER
IS
RETVAL NUMBER;
SOGGETTO VARCHAR2(250);
NCONT  NUMBER;
NPOS   NUMBER;
BEGIN
   IF (P_RUOLO = 'AMM') THEN
       RETURN 1;
   END IF;
   RETVAL := 0;
   NCONT := 0;
   SOGGETTO := P_OGGETTO;
   WHILE ((NVL(SOGGETTO,' ') <> ' ') AND (RETVAL = 0)) LOOP
      NCONT := NCONT + 1;
        RETVAL := GDM_COMPETENZA.GDM_VERIFICA(P_TIPO_OGGETTO,SOGGETTO,
                                       P_TIPO_ABILITAZIONE,P_UTENTE,
                              P_RUOLO,P_DATA);
     NPOS := INSTR(P_OGGETTO,'.',-1,NCONT) - 1;
      SOGGETTO := SUBSTR(P_OGGETTO,0,NPOS);
   END LOOP;
   RETURN RETVAL;
END;
/

