CREATE OR REPLACE FUNCTION F_VISTA_DOCUMENTO(A_DOCUMENTO VARCHAR2)
RETURN VARCHAR2 IS
/*  BY ANDREA*/
   DESCR VARCHAR2(2000) := NULL;
CURSOR C_1 IS
    SELECT NOME|| '  '||NVL(DBMS_LOB.SUBSTR(VALORE_CLOB, 50,1), NVL(TO_CHAR(VALORE_DATA),TO_CHAR(VALORE_NUMERO) )) ABSTRACT
      FROM VALORI VA, CAMPI_DOCUMENTO C
     WHERE VA.ID_DOCUMENTO   = A_DOCUMENTO
    AND VA.ID_CAMPO = C.ID_CAMPO
      ;
 BEGIN
   BEGIN
       FOR C1 IN C_1 LOOP
         DESCR := LTRIM(DESCR ||C1.ABSTRACT||'... ', '... ') ;
      END LOOP;
      IF DESCR IS NULL THEN
         RETURN 'Documento n. '|| A_DOCUMENTO;
      END IF;
   END;
   RETURN DESCR;
 END F_VISTA_DOCUMENTO;
/

