CREATE OR REPLACE FUNCTION MANAGE_OGGETTIFILECHECK (IDOGGETTO NUMBER, UTE VARCHAR2)
RETURN NUMBER IS
 NUMCHECK NUMBER(10);
 CONTA    NUMBER(10);
 PRAGMA autonomous_transaction;
 BEGIN
        SELECT count(*)
        INTO CONTA
        FROM OGGETTI_FILE_CHECK
        WHERE UTENTE=UTE
         AND ID_OGGETTO_FILE=IDOGGETTO;
        SELECT MAX(NUM_CHECK) INTO NUMCHECK FROM OGGETTI_FILE_CHECK WHERE ID_OGGETTO_FILE=IDOGGETTO;
    BEGIN
        IF CONTA>0 THEN
            UPDATE OGGETTI_FILE_CHECK
               SET NUM_CHECK=NVL(NUMCHECK,1),
                 DATA_AGGIORNAMENTO=SYSDATE
            WHERE UTENTE=UTE
             AND ID_OGGETTO_FILE=IDOGGETTO;
        ELSE
            INSERT INTO
            OGGETTI_FILE_CHECK
            (ID_OGGETTO_FILE,UTENTE,NUM_CHECK,DATA_AGGIORNAMENTO)
          VALUES
          (IDOGGETTO,UTE,NVL(NUMCHECK,1),SYSDATE);
        END IF;
        EXCEPTION WHEN OTHERS THEN
             if DBMS_UTILITY.FORMAT_ERROR_STACK  like  '%ORA-00060%' then
                 ROLLBACK;
                 RETURN 0;
             else
                ROLLBACK;
                RAISE;
                RETURN -1;
             end if;
    END;
    COMMIT;
    RETURN 0;
 END;
/

