CREATE TABLE ALIAS_IN_CARTELLA
(
  ID_ALIASINCARTELLA  NUMBER(10)                NOT NULL,
  ID_VIEWCARTELLA     NUMBER(10),
  ID_ALIASCAMPO       NUMBER(10),
  VISIBILE            VARCHAR2(1 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


