CREATE TABLE ALLEGATI
(
  CODICE_RICHIESTA  VARCHAR2(100 BYTE)          NOT NULL,
  AREA              VARCHAR2(200 BYTE)          NOT NULL,
  CODICE_ALLEGATO   VARCHAR2(255 BYTE)          NOT NULL,
  ALLEGATO          BLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE ALLEGATI IS 'Allegati al modello (binari e non).';



