CREATE TABLE ALLEGATI_TEMP_PERCORSI
(
  AREA                  VARCHAR2(200 BYTE)      NOT NULL,
  CODICE_MODELLO        VARCHAR2(50 BYTE)       NOT NULL,
  CODICE_RICHIESTA      VARCHAR2(100 BYTE)      NOT NULL,
  NOMEFILE              VARCHAR2(200 BYTE)      NOT NULL,
  PERCORSO              VARCHAR2(2000 BYTE),
  PERCORSO_ROOT         VARCHAR2(1000 BYTE),
  PERCORSO_NOFILE       VARCHAR2(2000 BYTE),
  STATO                 VARCHAR2(1 BYTE),
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE),
  DATA_AGGIORNAMENTO    DATE                    DEFAULT SYSDATE               NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


