CREATE TABLE CATEGORIE
(
  CATEGORIA             VARCHAR2(20 BYTE)       NOT NULL,
  DESCRIZIONE           VARCHAR2(100 BYTE),
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        NOT NULL,
  ISTRUZIONE            VARCHAR2(2000 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


