CREATE TABLE CLASSIFICAZIONI
(
  ID_CLASSIFICAZIONE  NUMBER(10)                NOT NULL,
  AREA                VARCHAR2(200 BYTE),
  DATO                VARCHAR2(30 BYTE),
  CLASSIFICAZIONE     VARCHAR2(240 BYTE),
  DESCRIZIONE         VARCHAR2(60 BYTE),
  NOTE                VARCHAR2(2000 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


