CREATE TABLE COLLEGAMENTI
(
  ID_COLLEGAMENTO        NUMBER(10)             NOT NULL,
  ID_CARTELLA            NUMBER(10)             NOT NULL,
  ID_CARTELLA_COLLEGATA  NUMBER(10),
  DATA_AGGIORNAMENTO     DATE                   NOT NULL,
  UTENTE_AGGIORNAMENTO   VARCHAR2(8 BYTE)       NOT NULL,
  CATEGORIA_COLLEGATA    VARCHAR2(64 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


