CREATE TABLE COMUNICAZIONI
(
  ID_COMUNICAZIONE  VARCHAR2(10 BYTE)           NOT NULL,
  ID_DOCUMENTO      NUMBER(10),
  MITTENTE          VARCHAR2(100 BYTE),
  DESTINARIO        VARCHAR2(100 BYTE),
  DATA              DATE
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


