CREATE TABLE CONTROLLI_CARTELLE
(
  ACTION_KEY   VARCHAR2(50 BYTE)                NOT NULL,
  AREA         VARCHAR2(200 BYTE)               NOT NULL,
  CONTROLLO    VARCHAR2(30 BYTE)                NOT NULL,
  ID_RISORSA   NUMBER(10),
  LABEL        VARCHAR2(50 BYTE)                NOT NULL,
  NASCONDI     VARCHAR2(200 BYTE),
  DESCRIZIONE  VARCHAR2(2000 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


