CREATE TABLE DESKTOP
(
  UTENTE       VARCHAR2(64 BYTE),
  GRUPPO       VARCHAR2(64 BYTE),
  CATEGORIA    VARCHAR2(64 BYTE),
  DESKTOP      VARCHAR2(64 BYTE),
  DESCRIZIONE  VARCHAR2(256 BYTE),
  QUERYSQL     VARCHAR2(4000 BYTE)              DEFAULT 'select 1 from attivita where 1 = 1 '
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


