CREATE TABLE DIZIONARI
(
  ID_DIZIONARIO  NUMBER(10)                     NOT NULL,
  DIZIONARIO     VARCHAR2(250 BYTE)             NOT NULL,
  DESCRIZIONE    VARCHAR2(2000 BYTE)            NOT NULL,
  PARAMETRO      VARCHAR2(100 BYTE)             NOT NULL,
  VALORE         VARCHAR2(100 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


