CREATE TABLE DR$GDM$MTES_FULL_TEXT_CTX$K
(
  DOCID    NUMBER,
  TEXTKEY  ROWID
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


