CREATE TABLE FORMATI_VIEWER
(
  ID_FORMATO_VIEWER     NUMBER(10)              NOT NULL,
  ID_VIEWER             NUMBER(10),
  ID_FORMATO            NUMBER(10),
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


