CREATE TABLE GDM_T_FIRMA_REPORT
(
  ID_DOCUMENTO          NUMBER(10)              NOT NULL,
  DATA_RICHIESTA        DATE,
  ID_TRANSACTION_FIRMA  VARCHAR2(10 BYTE),
  LOG_FIRMA             CLOB,
  UTENTE_FIRMA          VARCHAR2(10 BYTE),
  FULL_TEXT             CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


