CREATE TABLE GDM_T_MODELLO_TESTI
(
  ID_DOCUMENTO      NUMBER(10)                  NOT NULL,
  APPLICATIVO       VARCHAR2(100 BYTE),
  CARATTERISTICA    VARCHAR2(50 BYTE),
  DESCRIZIONE       VARCHAR2(1000 BYTE),
  ID_MODELLO_TESTI  VARCHAR2(100 BYTE),
  IN_USO            VARCHAR2(10 BYTE),
  TAG_FINALE        VARCHAR2(50 BYTE),
  TAG_INIZIALE      VARCHAR2(50 BYTE),
  TITOLO            VARCHAR2(50 BYTE),
  FULL_TEXT         CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


