CREATE TABLE GDM_T_FIRMA_LOG
(
  ID_DOCUMENTO          NUMBER(10)              NOT NULL,
  CODICE_ERRORE_FIRMA   VARCHAR2(200 BYTE),
  DATA_FIRMA            DATE,
  DATA_RICHIESTA        DATE,
  DESCR_ERRORE_FIRMA    VARCHAR2(2000 BYTE),
  IDRIF                 VARCHAR2(15 BYTE),
  ID_TRANSACTION_FIRMA  VARCHAR2(10 BYTE),
  LOG_FIRMA             CLOB,
  STATO_FIRMA           VARCHAR2(2 BYTE),
  UTENTE_FIRMA          VARCHAR2(10 BYTE),
  FULL_TEXT             CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


