CREATE TABLE GDM_ELAB_BATCH
(
  ID_DOCUMENTO         NUMBER(10)               NOT NULL,
  DATA_FINE            DATE,
  DATA_INIZIO          DATE,
  DESCRIZIONE          VARCHAR2(1000 BYTE),
  ERRORE_ELABORAZIONE  CLOB,
  ID_ELABORAZIONE      NUMBER(10),
  STATO_ELABORAZIONE   VARCHAR2(20 BYTE),
  TIPO_ELABORAZIONE    VARCHAR2(30 BYTE),
  UTENTE               VARCHAR2(20 BYTE),
  FULL_TEXT            CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


