CREATE TABLE GDM_T_REPORT_HEADER
(
  ID_DOCUMENTO       NUMBER(10)                 NOT NULL,
  MARGINE_DESTRO     VARCHAR2(5 BYTE),
  MARGINE_INFERIORE  VARCHAR2(5 BYTE),
  MARGINE_SINISTRO   VARCHAR2(5 BYTE),
  MARGINE_SUPERIORE  VARCHAR2(5 BYTE),
  TITOLO             VARCHAR2(50 BYTE),
  FULL_TEXT          CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


