CREATE TABLE IMPRONTE_FILE
(
  ID_DOCUMENTO  NUMBER(10)                      NOT NULL,
  FILENAME      VARCHAR2(200 BYTE)              NOT NULL,
  HASHCODE      VARCHAR2(128 BYTE)              NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


