CREATE TABLE KFX_PERCORSI_DOCUMENTI
(
  ID_DOCUMENTO        VARCHAR2(10 BYTE)         NOT NULL,
  PERCORSO_DOCUMENTO  VARCHAR2(2000 BYTE)       NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


