CREATE TABLE MAPPING_CAMPI
(
  ID_MAPPING_CAMPO      NUMBER(10)              NOT NULL,
  ID_MAPPING_TIPODOC    NUMBER(10)              NOT NULL,
  NOME                  VARCHAR2(100 BYTE)      NOT NULL,
  NOMEDM                VARCHAR2(100 BYTE)      NOT NULL,
  NOTE                  VARCHAR2(2000 BYTE),
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


