CREATE TABLE MODELLI_IMPORT
(
  AREA                  VARCHAR2(200 BYTE)      NOT NULL,
  CODICE_MODELLO        VARCHAR2(50 BYTE)       NOT NULL,
  DATA_AGGIORNAMENTO    DATE                    DEFAULT SYSDATE,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        DEFAULT 'GDM',
  CAMPI                 VARCHAR2(2000 BYTE),
  DESCRIZIONE           VARCHAR2(255 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


