CREATE TABLE OGGETTI_FILE_LOG
(
  ID_OGGETTO_FILE_LOG    NUMBER(10)             NOT NULL,
  ID_LOG                 NUMBER(10),
  ID_OGGETTO_FILE        NUMBER(10),
  FILENAME               VARCHAR2(200 BYTE),
  NOME_FORMATO           VARCHAR2(10 BYTE),
  TESTOOCR               BLOB,
  "FILE"                 BFILE,
  ALLEGATO               VARCHAR2(1 BYTE),
  DATA_AGGIORNAMENTO     DATE                   NOT NULL,
  UTENTE_AGGIORNAMENTO   VARCHAR2(8 BYTE)       NOT NULL,
  DATA_OPERAZIONE        DATE                   NOT NULL,
  UTENTE_OPERAZIONE      VARCHAR2(8 BYTE)       NOT NULL,
  TIPO_OPERAZIONE        VARCHAR2(1 BYTE)       NOT NULL,
  PATH_FILE              VARCHAR2(1000 BYTE),
  IMPRONTA               VARCHAR2(128 BYTE),
  PATH_FILE_ROOT         VARCHAR2(1000 BYTE),
  PATH_FILE_ROOT_ORACLE  VARCHAR2(1000 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


