CREATE TABLE PARAMETRI_SESSIONE
(
  APPLICATIVO     VARCHAR2(200 BYTE)            NOT NULL,
  NOME_PARAMETRO  VARCHAR2(200 BYTE)            NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


