CREATE TABLE REVISIONI_MODELLO
(
  AREA                  VARCHAR2(200 BYTE)      NOT NULL,
  CODICE_MODELLO        VARCHAR2(50 BYTE)       NOT NULL,
  REVISIONE             VARCHAR2(10 BYTE)       NOT NULL,
  ID_TIPODOC            NUMBER(10),
  CODICE_MODELLO_PADRE  VARCHAR2(50 BYTE),
  DATA_REVISIONE        DATE,
  VALIDO                VARCHAR2(1 BYTE),
  AUTORE                VARCHAR2(100 BYTE),
  DATA_INSERIMENTO      DATE,
  DATA_VARIAZIONE       DATE,
  DATA_PUBBLICAZIONE    DATE,
  NOTE_INTERNE          VARCHAR2(250 BYTE),
  NOTE                  VARCHAR2(250 BYTE),
  ISTRUZIONI            VARCHAR2(250 BYTE),
  DTD                   VARCHAR2(250 BYTE),
  MODELLO               CLOB,
  TIPO                  VARCHAR2(10 BYTE),
  OGGETTO               VARCHAR2(250 BYTE),
  CLASSIFICAZIONE       VARCHAR2(250 BYTE),
  ALLEGA_PDF            VARCHAR2(1 BYTE),
  MODELLO_SUCCESSIVO    VARCHAR2(50 BYTE),
  FILE_ORIGINALE        CLOB
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE REVISIONI_MODELLO IS 'Tabella dei template dei modelli.';



