CREATE TABLE RICHIESTE
(
  CODICE_RICHIESTA  VARCHAR2(100 BYTE)          NOT NULL,
  AREA              VARCHAR2(200 BYTE)          NOT NULL,
  ID_TIPO_PRATICA   NUMBER(10),
  DATA_SCADENZA     DATE,
  DATA_INSERIMENTO  DATE,
  CR_SOSTITUITO     VARCHAR2(100 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE RICHIESTE IS 'Richieste fatte.';



