CREATE TABLE RISORSE
(
  ID_RISORSA            NUMBER(10)              NOT NULL,
  RISORSA               BLOB,
  TIPO_OGGETTO          VARCHAR2(1 BYTE)        NOT NULL,
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


