CREATE TABLE SEMAFORI
(
  KEY             NUMBER(9)                     NOT NULL,
  ID_SEMAFORO     VARCHAR2(64 BYTE)             NOT NULL,
  ID_OGGETTO      VARCHAR2(64 BYTE)             NOT NULL,
  DATA_RICHIESTA  DATE,
  DATA_APERTURA   DATE,
  DATA_CHIUSURA   DATE,
  DESCRIZIONE     VARCHAR2(500 BYTE),
  UTENTE_BLOCCO   VARCHAR2(8 BYTE),
  UTENTE_SBLOCCO  VARCHAR2(8 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


