CREATE TABLE SYNCEXECTYPE
(
  EXECTYPE     VARCHAR2(20 BYTE)                NOT NULL,
  DESCRIZIONE  VARCHAR2(200 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


