CREATE TABLE SYNCJDMSCONTROL
(
  ID_SYNCACTIVITYCONTROL  NUMBER(10)            NOT NULL,
  EXECTYPE                VARCHAR2(20 BYTE)     NOT NULL,
  AREA                    VARCHAR2(200 BYTE)    NOT NULL,
  CONTROLLO               VARCHAR2(30 BYTE)     NOT NULL
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


