CREATE TABLE TIPI_DOCUMENTO
(
  ID_TIPODOC            NUMBER(10)              NOT NULL,
  ID_LIBRERIA           NUMBER(10)              NOT NULL,
  NOME                  VARCHAR2(100 BYTE)      NOT NULL,
  VERSIONABILE          VARCHAR2(1 BYTE)        NOT NULL,
  TIPO_LOG              VARCHAR2(1 BYTE)        NOT NULL,
  MANAGE_COMPETENZE     VARCHAR2(1 BYTE)        DEFAULT '1'                   NOT NULL,
  GESTIONE_COMPETENZE   VARCHAR2(1 BYTE)        NOT NULL,
  ID_PROCEDIMENTO       NUMBER(10),
  ATTIVAPRATICA         VARCHAR2(1 BYTE)        NOT NULL,
  NOTE                  VARCHAR2(2000 BYTE),
  ALIAS_VIEW            VARCHAR2(26 BYTE),
  ICONA                 VARCHAR2(50 BYTE),
  DATA_AGGIORNAMENTO    DATE                    NOT NULL,
  UTENTE_AGGIORNAMENTO  VARCHAR2(8 BYTE)        NOT NULL,
  AREA_MODELLO          VARCHAR2(200 BYTE),
  ACRONIMO_MODELLO      VARCHAR2(5 BYTE),
  ALIAS_MODELLO         VARCHAR2(26 BYTE),
  ISHORIZONTAL_MODEL    NUMBER(1),
  LOG_FILE              VARCHAR2(1 BYTE)        DEFAULT 'N',
  COMPETENZE_ALLEGATI   VARCHAR2(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  ICONA_EXP             VARCHAR2(4000 BYTE)
)
TABLESPACE GDM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

COMMENT ON TABLE TIPI_DOCUMENTO IS '
';

COMMENT ON COLUMN TIPI_DOCUMENTO.MANAGE_COMPETENZE IS 'Competenza di assegnare le competenze';



