CREATE OR REPLACE FORCE VIEW AGP_FILE_DOC_COLLEGATI_FAKE
(ID_DOCUMENTO, ID_DOCUMENTO_ESTERNO, ID_FILE_DOCUMENTO, ID_FILE_ESTERNO, ID_DOC_AGSPR_PADRE, 
 ID_DOC_ESTERNO_AGSPR_PADRE)
BEQUEATH DEFINER
AS 
SELECT 0,0,0,0,0,0 FROM DUAL WHERE 1<>1;


