CREATE OR REPLACE FORCE VIEW CART_FOGLIE_JS
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, COMPETENZA, ID_CARTELLA, 
 ID_OGGETTO)
BEQUEATH DEFINER
AS 
SELECT  'C'||ID_CARTELLA PARENTID, TIPO_OGGETTO||ID_OGGETTO NODEID, F_LINK_JS(ID_OGGETTO, TIPO_OGGETTO) TEXT,
TO_CHAR(NULL) URL, TO_CHAR(NULL) TOOLTIP, 'folder.gif' CUSTOM_IMAGE, TO_CHAR(NULL) DEFAULT_IMAGE,
TO_CHAR(NULL) CUSTOM_STYLE,
F_TIPO_COMPETENZA(ID_OGGETTO, TIPO_OGGETTO) COMPETENZA,
ID_CARTELLA, ID_OGGETTO FROM LINKS l1
where tipo_oggetto = 'C'
and not exists ( SELECT '' FROM links l2 where l2.id_cartella=l1.id_oggetto)
start with  ID_CARTELLA   IN (SELECT to_number(replace(NODEID,'C','')) FROM radici)
--start with  'C'||ID_CARTELLA   IN (SELECT NODEID FROM RADICI )
CONNECT BY  prior ID_OGGETTO =   ID_CARTELLA
and  prior tipo_oggetto =  'C';


