CREATE OR REPLACE FORCE VIEW COMPETENZE_FUNZIONALI
(AREA, CODICE_MODELLO, DESCRIZIONE, NOME, ID_COMPETENZA, 
 ID_ABILITAZIONE, UTENTE, OGGETTO, ACCESSO, RUOLO, 
 DAL, AL, DATA_AGGIORNAMENTO, UTENTE_AGGIORNAMENTO, ID_FUNZIONE, 
 TIPO_COMPETENZA)
BEQUEATH DEFINER
AS 
SELECT M.AREA, M.CODICE_MODELLO, TIAB.DESCRIZIONE, FUNZ.NOME, S."ID_COMPETENZA",S."ID_ABILITAZIONE",S."UTENTE",S."OGGETTO",S."ACCESSO",S."RUOLO",S."DAL",S."AL",S."DATA_AGGIORNAMENTO",S."UTENTE_AGGIORNAMENTO",S."ID_FUNZIONE",S."TIPO_COMPETENZA"
FROM SI4_COMPETENZE S
    , SI4_ABILITAZIONI AB
    , SI4_TIPI_ABILITAZIONE TIAB
    , SI4_FUNZIONI FUNZ
    , MODELLI M
WHERE TIPO_COMPETENZA = 'F'
 AND S.ID_ABILITAZIONE IN (17, 18,19,20,37,40,43)
 AND S.ID_ABILITAZIONE = AB.ID_ABILITAZIONE
 AND AB.ID_TIPO_ABILITAZIONE = TIAB.ID_TIPO_ABILITAZIONE
 AND S.ID_FUNZIONE = FUNZ.ID_FUNZIONE
 AND S.OGGETTO = M.ID_TIPODOC
ORDER BY M.AREA, M.CODICE_MODELLO, S.ID_ABILITAZIONE, S.UTENTE;


