CREATE OR REPLACE FORCE VIEW FOGLIE
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, COMPETENZA, ID_CARTELLA, 
 TIPO_OGGETTO, ID_OGGETTO)
BEQUEATH DEFINER
AS 
SELECT  'C'||ID_CARTELLA PARENTID, TIPO_OGGETTO||ID_OGGETTO NODEID, F_LINK(ID_OGGETTO, TIPO_OGGETTO) TEXT ,
 decode(tipo_oggetto,'Q','parent.document.getElementById(''workArea'').src=''WorkArea.do?idQuery='||ID_OGGETTO||'&idCartAppartenenza='||ID_CARTELLA||'''',null) URL,
 TO_CHAR(NULL) TOOLTIP, decode(tipo_oggetto,'Q','qrysearch.gif',null) CUSTOM_IMAGE, TO_CHAR(NULL) DEFAULT_IMAGE,
 TO_CHAR(NULL) CUSTOM_STYLE , F_TIPO_COMPETENZA(ID_OGGETTO, TIPO_OGGETTO) COMPETENZA, ID_CARTELLA, TIPO_OGGETTO, ID_OGGETTO FROM LINKS
where tipo_oggetto = 'Q';


