CREATE OR REPLACE FORCE VIEW GD4_TREE
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, TIPO_OGGETTO, 
 ID_OGGETTO)
BEQUEATH DEFINER
AS 
SELECT  PARENTID PARENTID, NODEID, TEXT, URL,
       TOOLTIP, CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA,
       'C' TIPO_OGGETTO, ID_OGGETTO
  FROM CART_FOGLIE
 UNION ALL
 SELECT  PARENTID PARENTID, NODEID, TEXT, URL,
       TOOLTIP, DEFAULT_IMAGE, CUSTOM_IMAGE, CUSTOM_STYLE, ID_CARTELLA,
       TIPO_OGGETTO, ID_OGGETTO
  FROM FOGLIE
 WHERE (COMPETENZA IN ('U','S') OR COMPETENZA = 'DONTCARE');


