CREATE OR REPLACE FORCE VIEW GD4_TREE_QUERY
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, TIPO_OGGETTO, 
 ID_OGGETTO)
BEQUEATH DEFINER
AS 
SELECT  '0' PARENTID,NODEID,TEXT,URL,TOOLTIP,CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, TIPO_OGGETTO, ID_OGGETTO FROM FOGLIE
 WHERE  TIPO_OGGETTO = 'Q'
 AND ID_CARTELLA = '-3';


