CREATE OR REPLACE FORCE VIEW GD4_TREE_USER_JS
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, TIPO_OGGETTO, 
 ID_OGGETTO)
BEQUEATH DEFINER
AS 
SELECT DECODE(ID_CARTELLA, '-2', '0', PARENTID) PARENTID,NODEID,TEXT,URL,TOOLTIP,CUSTOM_IMAGE, 'folder.gif' DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, 'C' TIPO_OGGETTO,  ID_OGGETTO FROM CART_INTERMEDIE_JS
 WHERE COMPETENZA = 'U'
 UNION ALL
 SELECT DECODE(ID_CARTELLA, '-2', '0', PARENTID) PARENTID,NODEID,TEXT,URL,TOOLTIP,CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, ID_CARTELLA, 'C' TIPO_OGGETTO, ID_OGGETTO FROM CART_FOGLIE_JS
 WHERE COMPETENZA = 'U';


