CREATE OR REPLACE FORCE VIEW GDM_MODELLO_MANUALI
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 TITOLO, DESCRIZIONE, APPLICATIVO, ID_MODELLLO_TESTI, IN_USO)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'MODELLO_MANUALI',D.STATO_DOCUMENTO, T.TITOLO, T.DESCRIZIONE, T.APPLICATIVO, T.ID_MODELLLO_TESTI, T.IN_USO FROM DOCUMENTI D, GDM_T_MODELLO_MANUALI T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 8;

COMMENT ON TABLE GDM_MODELLO_MANUALI IS 'Area: GDMSYS - Modello: MODELLO_MANUALI';



