CREATE OR REPLACE FORCE VIEW GDM_FIRMA_REPORT
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 DATA_RICHIESTA, UTENTE_FIRMA, LOG_FIRMA, ID_TRANSACTION_FIRMA)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'FIRMA_REPORT',D.STATO_DOCUMENTO, TO_CHAR(T.DATA_RICHIESTA,'dd/mm/yyyy hh:mi:ss'), T.UTENTE_FIRMA, T.LOG_FIRMA, T.ID_TRANSACTION_FIRMA FROM DOCUMENTI D, GDM_T_FIRMA_REPORT T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 1;

COMMENT ON TABLE GDM_FIRMA_REPORT IS 'Area: GDMSYS - Modello: FIRMA_REPORT';



