CREATE OR REPLACE FORCE VIEW GDM_WRKSPSTANDARD
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 NOME)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'WRKSPStandard',D.STATO_DOCUMENTO, T.NOME FROM DOCUMENTI D, GDM_W_WORKSPACESTANDARD T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 16;

COMMENT ON TABLE GDM_WRKSPSTANDARD IS 'Area: GDMSYS - Modello: WRKSPStandard';



