CREATE OR REPLACE FORCE VIEW GDM_CARTELLASTANDARD
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 NOME)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'CartellaStandard',D.STATO_DOCUMENTO, T.NOME FROM DOCUMENTI D, GDM_C_CARTELLASTANDARD T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 6;

COMMENT ON TABLE GDM_CARTELLASTANDARD IS 'Area: GDMSYS - Modello: CartellaStandard';



