CREATE OR REPLACE FORCE VIEW GDM_REPORT_HEADER
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 TITOLO, MARGINE_SUPERIORE, MARGINE_INFERIORE, MARGINE_DESTRO, MARGINE_SINISTRO)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'REPORT_HEADER',D.STATO_DOCUMENTO, T.TITOLO, T.MARGINE_SUPERIORE, T.MARGINE_INFERIORE, T.MARGINE_DESTRO, T.MARGINE_SINISTRO FROM DOCUMENTI D, GDM_T_REPORT_HEADER T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 11;

COMMENT ON TABLE GDM_REPORT_HEADER IS 'Area: GDMSYS - Modello: REPORT_HEADER';



