CREATE OR REPLACE FORCE VIEW GDM_FIRMA_LOG
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 ID_TRANSACTION_FIRMA, DATA_RICHIESTA, DATA_FIRMA, CODICE_ERRORE_FIRMA, DESCR_ERRORE_FIRMA, 
 IDRIF, LOG_FIRMA, STATO_FIRMA, UTENTE_FIRMA)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'FIRMA_LOG',D.STATO_DOCUMENTO, T.ID_TRANSACTION_FIRMA, TO_CHAR(T.DATA_RICHIESTA,'dd/mm/yyyy hh:mi:ss'), TO_CHAR(T.DATA_FIRMA,'dd/mm/yyyy hh:mi:ss'), T.CODICE_ERRORE_FIRMA, T.DESCR_ERRORE_FIRMA, T.IDRIF, T.LOG_FIRMA, T.STATO_FIRMA, T.UTENTE_FIRMA FROM DOCUMENTI D, GDM_T_FIRMA_LOG T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 3;

COMMENT ON TABLE GDM_FIRMA_LOG IS 'Area: GDMSYS - Modello: FIRMA_LOG';



