CREATE OR REPLACE FORCE VIEW GDM_MODELLO_TESTI
(DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 TITOLO, DESCRIZIONE, APPLICATIVO, ID_MODELLO_TESTI, IN_USO, 
 CARATTERISTICA, TAG_INIZIALE, TAG_FINALE)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,D.CODICE_RICHIESTA, D.AREA,'MODELLO_TESTI',D.STATO_DOCUMENTO, T.TITOLO, T.DESCRIZIONE, T.APPLICATIVO, T.ID_MODELLO_TESTI, T.IN_USO, T.CARATTERISTICA, T.TAG_INIZIALE, T.TAG_FINALE FROM DOCUMENTI D, GDM_T_MODELLO_TESTI T WHERE D.ID_DOCUMENTO = T.ID_DOCUMENTO AND D.ID_TIPODOC = 9;

COMMENT ON TABLE GDM_MODELLO_TESTI IS 'Area: GDMSYS - Modello: MODELLO_TESTI';



