CREATE OR REPLACE FORCE VIEW GLOSSARIO_TREE
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, CUSTOM_STYLE)
BEQUEATH DEFINER
AS 
SELECT
  DECODE(ID_FRASE_PADRE,0,'0',AREA || '-' || TO_CHAR(ID_FRASE_PADRE)) PARENTID,
  AREA || '-' ||TO_CHAR(ID_FRASE) NODEID,
  TITOLO TEXT,
  DECODE(NVL(FRASE,'-'),'-',DECODE(NVL(BLOCCO,''),'','','javascript:apriPopup('||''''||BLOCCO||''''||')'),'javascript:myInsertHTML('||''''||REPLACE(REPLACE(FRASE,'''','\'''),CHR(13)||CHR(10),'<br/>')||''''||')') URL,
  '' TOOLTIP,
  '' CUSTOM_IMAGE,
  '' CUSTOM_STYLE
FROM
  FRASI_GLOSSARIO;


