CREATE OR REPLACE FORCE VIEW INDICI_DATI
(AREA, DATO, AREA_MODELLO, CODICE_MODELLO, ID_CAMPO, 
 ACRONIMO_DATO, MODALITA_RICERCA, INDICE_GENERATO, NOME_TABELLA, NOME_INDICE)
BEQUEATH DEFINER
AS 
SELECT D.AREA,
        D.DATO,
        DM.AREA AREA_MODELLO,
        DM.CODICE_MODELLO,
        DM.ID_CAMPO,
        D.ACRONIMO_DATO,
        C.MODALITA_RICERCA,
        C.INDICE_GENERATO,
        F_NOME_TABELLA(DM.AREA, DM.CODICE_MODELLO) AS NOME_TABELLA,
        F_NOME_INDICE(DM.AREA, DM.CODICE_MODELLO, D.DATO) AS NOME_INDICE
   FROM DATI D,
        DATI_MODELLO DM,
        CAMPI_DOCUMENTO C
  WHERE D.AREA = DM.AREA_DATO
    AND D.DATO = DM.DATO
    AND DM.ID_CAMPO = C.ID_CAMPO;


