CREATE OR REPLACE FORCE VIEW RADICI
(PARENTID, NODEID, TEXT, URL, TOOLTIP, 
 CUSTOM_IMAGE, DEFAULT_IMAGE, CUSTOM_STYLE, COMPETENZA, ID_CARTELLA)
BEQUEATH DEFINER
AS 
SELECT '0' PARENTID, 'C'||ID_CARTELLA NODEID,NOME TEXT, TO_CHAR(NULL) URL,TO_CHAR(NULL)  TOOLTIP,
	   TO_CHAR(NULL) CUSTOM_IMAGE, TO_CHAR(NULL) DEFAULT_IMAGE, TO_CHAR(NULL) CUSTOM_STYLE , TIPO COMPETENZA , ID_CARTELLA FROM CARTELLE
 WHERE  ID_CARTELLA  < 0;


