CREATE OR REPLACE FORCE VIEW VIEW_DOCUMENTI_PROTOCOLLATI
(ID_DOCUMENTO, CODICE_RICHIESTA, AREA, CODICE_MODELLO, STATO, 
 TIPOREGISTRO, DATA, IDRIF)
BEQUEATH DEFINER
AS 
SELECT D.ID_DOCUMENTO,
       D.CODICE_RICHIESTA,
       D.AREA,
       M.CODICE_MODELLO,
       F_STATO_DOCUMENTO(D.ID_DOCUMENTO) STATO,
       F_VALORE_CAMPO(D.ID_DOCUMENTO,'TIPO_REGISTRO') TIPOREGISTRO,F_VALORE_CAMPO(D.ID_DOCUMENTO,'DATA') DATA,
       F_VALORE_CAMPO(D.ID_DOCUMENTO,'IDRIF') IDRIF
  FROM DOCUMENTI D, MODELLI M
 WHERE M.ID_TIPODOC=D.ID_TIPODOC AND
 (SELECT  F_VALORE(ID_DOCUMENTO,CD.ID_CAMPO)
 FROM CAMPI_DOCUMENTO CD, VALORI VA
 WHERE NOME='$ANNO' AND
      CD.ID_CAMPO=VA.ID_CAMPO AND
	  ID_DOCUMENTO=D.ID_DOCUMENTO  ) IS NOT NULL AND
 (SELECT  F_VALORE(ID_DOCUMENTO,CD.ID_CAMPO)
 FROM CAMPI_DOCUMENTO CD, VALORI VA
 WHERE NOME='$NUMPROT' AND
      CD.ID_CAMPO=VA.ID_CAMPO AND
	  ID_DOCUMENTO=D.ID_DOCUMENTO  ) IS NOT NULL
ORDER BY 1;


