CREATE OR REPLACE FORCE VIEW VIEW_LUNGHEZZE
(AREA, CODICE_MODELLO, ID_TIPODOC, TIPO, DATO, 
 ID_CAMPO, LUNGHEZZA, LUNGHEZZA_EFFETTIVA)
BEQUEATH DEFINER
AS 
SELECT T.AREA_MODELLO AREA, T.NOME CODICE_MODELLO, T.ID_TIPODOC, D.TIPO,
       D.DATO, V.ID_CAMPO, D.LUNGHEZZA, NVL (LENGTH (VALORE_STRINGA), 0) LUNGHEZZA_EFFETTIVA
  FROM VALORI V, DATI D, TIPI_DOCUMENTO T, DATI_MODELLO DM,
  CARICA_DATI_ERRORI C
 WHERE D.DATO = DM.DATO
   AND D.AREA = DM.AREA_DATO
   AND DM.ID_CAMPO = V.ID_CAMPO
   AND T.AREA_MODELLO = DM.AREA
   AND T.NOME = DM.CODICE_MODELLO
   AND D.TIPO = 'S'
   AND V.ID_DOCUMENTO = C.IDDOC
   AND NVL (LENGTH (VALORE_STRINGA), 0) > D.LUNGHEZZA
 UNION ALL
 SELECT T.AREA_MODELLO AREA, T.NOME CODICE_MODELLO, T.ID_TIPODOC, D.TIPO,
       D.DATO, V.ID_CAMPO, D.LUNGHEZZA, NVL (LENGTH (VALORE_NUMERO), 0) LUNGHEZZA_EFFETTIVA
  FROM VALORI V, DATI D, TIPI_DOCUMENTO T, DATI_MODELLO DM,
  CARICA_DATI_ERRORI C
 WHERE D.DATO = DM.DATO
   AND D.AREA = DM.AREA_DATO
   AND DM.ID_CAMPO = V.ID_CAMPO
   AND T.AREA_MODELLO = DM.AREA
   AND T.NOME = DM.CODICE_MODELLO
   AND D.TIPO = 'N'
   AND V.ID_DOCUMENTO = C.IDDOC
   AND NVL (LENGTH (VALORE_NUMERO), 0) > D.LUNGHEZZA;


