CREATE OR REPLACE FORCE VIEW VISTE_MODELLI
(AREA, CODICE_MODELLO, TIPO_DOCUMENTO, NOME_VISTA1, NOME_VISTA2)
BEQUEATH DEFINER
AS 
SELECT AREA, CODICE_MODELLO, ID_TIPODOC TIPO_DOCUMENTO,
 UPPER('GDM_'||AREA||'_'||CODICE_MODELLO) NOME_VISTA1, UPPER('GDM_'||ID_TIPODOC) NOME_VISTA2
 FROM MODELLI;


