CREATE UNIQUE INDEX ALIAS_CAMPI_PK ON ALIAS_CAMPI
(ID_ALIASCAMPO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


