CREATE UNIQUE INDEX ALIAS_IN_CARTELLA_PK ON ALIAS_IN_CARTELLA
(ID_ALIASINCARTELLA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


