CREATE UNIQUE INDEX ALLEGATI_DOCUMENTI_REGOLE_PK ON ALLEGATI_DOCUMENTI_REGOLE
(AREA, CODICE_MODELLO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


