CREATE UNIQUE INDEX ALLEGATI_TEMP_PERCORSI_PK ON ALLEGATI_TEMP_PERCORSI
(AREA, CODICE_MODELLO, CODICE_RICHIESTA, NOMEFILE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


