CREATE UNIQUE INDEX AMV_DOCUMENTI_PK ON AMV_DOCUMENTI
(ID_DOCUMENTO, REVISIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


