CREATE INDEX AMV_CLAS_CATE_FK ON AMV_CLASSIFICAZIONI
(ID_CATEGORIA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


