CREATE UNIQUE INDEX AMV_DOCUMENTI_BLOB_PK ON AMV_DOCUMENTI_BLOB
(ID_DOCUMENTO, REVISIONE, ID_BLOB)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


