CREATE UNIQUE INDEX APPL_ENTE_NOME_UK ON MAPPING_TIPIDOC
(APPLICATIVO, ENTE, NOME)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


