CREATE UNIQUE INDEX AREE_PATH_PK ON AREE_PATH
(ID_PATH_AREE_FILE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


