CREATE INDEX CAMO_CATE_IDX ON CATEGORIE_MODELLO
(CATEGORIA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


