CREATE UNIQUE INDEX CARICA_DATI_ERRORI_PK ON CARICA_DATI_ERRORI
(IDDOC)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


