CREATE UNIQUE INDEX CATEGORIE_MODELLO_PK ON CATEGORIE_MODELLO
(AREA, CODICE_MODELLO, CATEGORIA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


