CREATE UNIQUE INDEX CLASSIFICAZIONI_PK ON CLASSIFICAZIONI
(ID_CLASSIFICAZIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


