CREATE UNIQUE INDEX CODICEADS_COES_UK ON COLLEGAMENTI_ESTERNI
(CODICEADS)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


