CREATE UNIQUE INDEX COLLEGAMENTI_ESTERNI_PK ON COLLEGAMENTI_ESTERNI
(ID_COLLEGAMENTO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


