CREATE UNIQUE INDEX COMUNICAZIONI_PK ON COMUNICAZIONI
(ID_COMUNICAZIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


