CREATE UNIQUE INDEX CONFIGURAZIONI_SISTEMA_PK ON CONFIGURAZIONI_SISTEMA
(ID_CONFSYS)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


