CREATE UNIQUE INDEX CS_MESSAGGI_LOG_PK ON CS_MESSAGGI_LOG
(ID_DOCUMENTO, MESSAGGIO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


