CREATE UNIQUE INDEX DIZIONARIO_LINGUA_PK ON DIZIONARIO_LINGUA
(ESPRESSIONE, LINGUA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


