CREATE UNIQUE INDEX DIZIONARI_PK ON DIZIONARI
(ID_DIZIONARIO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


