CREATE INDEX DM_ERR_LOG_CAT_IDX ON DM_ERR_LOG
(CATEGORIA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


