CREATE UNIQUE INDEX DM_ERR_LOG_PK ON DM_ERR_LOG
(ID_ERR_LOG)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


