CREATE INDEX DM_ERR_LOG_RIGHE_TAG_IDX ON DM_ERR_LOG_RIGHE
(TAG_FASE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


