CREATE UNIQUE INDEX DM_ERR_LOG_USERLEVEL_PK ON DM_ERR_LOG_USERLEVEL
(UTENTE, CATEGORIA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


