CREATE UNIQUE INDEX DM_SYSTEM_PK ON DM_SYSTEM
(ID_DM)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


