CREATE UNIQUE INDEX DR$GDM$WSTD_FULL_TEXT_CTX$KR ON DR$GDM$WSTD_FULL_TEXT_CTX$K
(TEXTKEY, DOCID)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


