CREATE UNIQUE INDEX DR$GDM$MTES_GDM$APPL_CTX$X ON DR$GDM$MTES_GDM$APPL_CTX$I
(DR$TOKEN, DR$TOKEN_TYPE, DR$ROWID)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
COMPRESS 2;


