CREATE UNIQUE INDEX DR$GDM$ELBT_FULL_TEXT_CTX$KD ON DR$GDM$ELBT_FULL_TEXT_CTX$K
(DOCID, TEXTKEY)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


