CREATE UNIQUE INDEX DR$GDM$MTES_FULL_TEXT_CTX$KR ON DR$GDM$MTES_FULL_TEXT_CTX$K
(TEXTKEY, DOCID)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


