CREATE INDEX DR$GDM$MTES_GDM$APPL_CTX$R ON DR$GDM$MTES_GDM$APPL_CTX$I
(DR$ROWID)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


