CREATE UNIQUE INDEX DR$OGFI_TEOC_CTX$KD ON DR$OGFI_TEOC_CTX$K
(DOCID, TEXTKEY)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


