CREATE UNIQUE INDEX FORMATI_VIEWER_PK ON FORMATI_VIEWER
(ID_FORMATO_VIEWER)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


