CREATE UNIQUE INDEX FRASI_GLOSSARIO_PK ON FRASI_GLOSSARIO
(ID_FRASE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


