CREATE UNIQUE INDEX GDM_ANALISI_SPAZIOFILE_PK ON GDM_ANALISI_SPAZIOFILE
(TIPO_MODELLO, TIPO_OGGETTO_FILE, POSIZIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


