CREATE INDEX ID_CART_COLL_IDX ON COLLEGAMENTI
(ID_CARTELLA_COLLEGATA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


