CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS
(SCHED_NAME, TRIGGER_GROUP)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


