CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS
(SCHED_NAME, JOB_GROUP)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


