CREATE UNIQUE INDEX IMPRONTE_FILE_PK ON IMPRONTE_FILE
(ID_DOCUMENTO, FILENAME)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


