CREATE UNIQUE INDEX ITEM_UK ON SYSINTEGRATION_PENDING
(TYPE_INTEGRATION, ID_DOCUMENTO, XML_OPTION_OTHERKEY)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   164
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


