CREATE INDEX KECO_IK ON KEY_CONSTRAINT
(TIPO, RIF_OGGETTO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


