CREATE UNIQUE INDEX KFX_PERCORSI_DOCUMENTI_PK ON KFX_PERCORSI_DOCUMENTI
(ID_DOCUMENTO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


