CREATE UNIQUE INDEX KFX_DATI_DOCUMENTO_PK ON KFX_DATI_DOCUMENTO
(ID_DOCUMENTO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


