CREATE UNIQUE INDEX LOG_INOLTRI_PK ON LOG_INOLTRI
(CODICE_RICHIESTA, AREA, ID_OP)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


