CREATE UNIQUE INDEX MAPPING_TIPIDOC_PK ON MAPPING_TIPIDOC
(ID_MAPPING_TIPODOC)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


