CREATE UNIQUE INDEX MAPPING_CAMPI_PK ON MAPPING_CAMPI
(ID_MAPPING_CAMPO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


