CREATE UNIQUE INDEX MAPPING_SYSTEM_PK ON MAPPING_SYSTEM
(ID_MAPPING_SYSTEM)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


