CREATE UNIQUE INDEX MAPTIPO_NOME_UK ON MAPPING_CAMPI
(ID_MAPPING_TIPODOC, NOME)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


