CREATE INDEX MASY_APPL_FK ON MAPPING_SYSTEM
(ID_APPLICATIVO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


