CREATE UNIQUE INDEX MASY_UK ON MAPPING_SYSTEM
(ID_ENTE, ID_APPLICATIVO, REVISIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


