CREATE UNIQUE INDEX MODELLI_TIPI_PRATICHE_PK ON MODELLI_TIPI_PRATICHE
(ID_MTP)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


