CREATE UNIQUE INDEX NOTIFICHE_PK ON NOTIFICHE
(ID_NOTIFICA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


