CREATE INDEX OGFI_IDLOG_IDX ON OGGETTI_FILE_LOG
(ID_LOG)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


