CREATE UNIQUE INDEX OGGETTI_FILE_CHECK_PK ON OGGETTI_FILE_CHECK
(ID_OGGETTO_FILE, UTENTE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


