CREATE UNIQUE INDEX OGGETTI_FILE_LOG_PK ON OGGETTI_FILE_LOG
(ID_OGGETTO_FILE_LOG)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


