CREATE UNIQUE INDEX PARAMETRI_POPUP_PK ON PARAMETRI_POPUP
(AREA, BLOCCO, PARAMETRO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


