CREATE UNIQUE INDEX PARAMETRI_SESSIONE_PK ON PARAMETRI_SESSIONE
(APPLICATIVO, NOME_PARAMETRO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


