CREATE UNIQUE INDEX PERSONALIZZAZIONI_PK ON PERSONALIZZAZIONI
(ID_PERSONALIZZAZIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


