CREATE UNIQUE INDEX PK_ALLEGATI ON ALLEGATI
(CODICE_RICHIESTA, AREA, CODICE_ALLEGATO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


