CREATE UNIQUE INDEX PK_CONTROLLI_DATI ON CONTROLLI_DATI
(AREA, DATO, CONTROLLO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


