CREATE UNIQUE INDEX PK_DIRITTI_DI_ACCESSO ON DIRITTI_DI_ACCESSO
(CODICE_RICHIESTA, AREA, UTENTE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


