CREATE UNIQUE INDEX PK_GRAFICI_MODELLO ON GRAFICI_MODELLO
(AREA, CODICE_MODELLO, NOMEFILE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


