CREATE UNIQUE INDEX PK_REPOSITORYTEMP ON REPOSITORYTEMP
(CODICE_RICHIESTA, CODICE_MODELLO, PROGRESSIVO, AREA, DATO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


