CREATE UNIQUE INDEX PK_VALORI_DOMINIO ON VALORI_DOMINIO
(AREA, DOMINIO, CODICE_MODELLO, CODICE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


