CREATE UNIQUE INDEX PRE_INOLTRO_PK ON PRE_INOLTRO
(ID_OP, CODICE_RICHIESTA, CODICE_MODELLO, AREA, DATO, 
PROGRESSIVO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


