CREATE UNIQUE INDEX QRTZ_PAUSED_TRIG_GRPS_PK ON QRTZ_PAUSED_TRIGGER_GRPS
(SCHED_NAME, TRIGGER_GROUP)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


