CREATE UNIQUE INDEX QRTZ_FIRED_TRIGGER_PK ON QRTZ_FIRED_TRIGGERS
(SCHED_NAME, ENTRY_ID)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


