CREATE UNIQUE INDEX QRTZ_SCHEDULER_STATE_PK ON QRTZ_SCHEDULER_STATE
(SCHED_NAME, INSTANCE_NAME)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


