CREATE UNIQUE INDEX REVISIONI_MODELLO_PK ON REVISIONI_MODELLO
(AREA, CODICE_MODELLO, REVISIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


