CREATE UNIQUE INDEX RIF_ALT_UK ON RIFERIMENTI
(ID_DOCUMENTO_RIF, ID_DOCUMENTO, TIPO_RELAZIONE, AREA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


