CREATE UNIQUE INDEX RISORSE_VERSIONI_DOCU_PK ON RISORSE_VERSIONI_DOCU
(ID_DOCUMENTO, VERSIONE, NOMEFILE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


