CREATE UNIQUE INDEX SEQ_TIPOBJ_UK ON ORDINAMENTI_CARTELLA
(SEQ, TIPO_OBJ, ID_TIPODOC)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


