CREATE UNIQUE INDEX SYSINTEGRATION_PENDING_LOG_PK ON SYSINTEGRATION_PENDING_LOG
(IDLOGPENDING)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


