CREATE UNIQUE INDEX SYSINTEGRATION_TYPE_PK ON SYSINTEGRATION_TYPE
(TYPE_INTEGRATION)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


