CREATE UNIQUE INDEX SYSINTEGRATION_PENDING_PK ON SYSINTEGRATION_PENDING
(IDSYSPENDING)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


