CREATE UNIQUE INDEX SYSINTEGRATION_FIELD_PK ON SYSINTEGRATION_FIELD
(TYPE_INTEGRATION, AREA, CODICE_MODELLO, FIELD)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


