CREATE UNIQUE INDEX TIPI_PRATICHE_PK ON TIPI_PRATICHE
(ID_TIPO_PRATICA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


