CREATE UNIQUE INDEX TIPI_ALLEGATI_MODELLO_PK ON TIPI_ALLEGATI_MODELLO
(AREA, CODICE_MODELLO, FORMATO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


