CREATE UNIQUE INDEX TRIGGER_MODELLI_PK ON TRIGGER_MODELLI
(NOME, ID_TIPODOC)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


