CREATE INDEX TYPE_PEND_STATUS_IDX ON SYSINTEGRATION_PENDING
(TYPE_INTEGRATION, PENDING, LASTSTATUS)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


