CREATE INDEX UTENTE_BLOCCO_AK ON SEMAFORI
(UTENTE_BLOCCO)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


