CREATE UNIQUE INDEX VALORI_LOG_PK ON VALORI_LOG
(ID_VALORE_LOG)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


