CREATE INDEX VALOG_IDLOG_COLONNA_IDX ON VALORI_LOG
(COLONNA)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


