CREATE UNIQUE INDEX VERSIONI_DOCUMENTI_PK ON VERSIONI_DOCUMENTI
(ID_DOCUMENTO, VERSIONE)
TABLESPACE GDM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


