CREATE OR REPLACE PROCEDURE ASSEGNA_ETICHETTA(P_AREA IN VARCHAR2
, P_MODELLO IN VARCHAR2
, P_ETICHETTA IN VARCHAR2
, P_VALORE IN VARCHAR2
, P_ICONA IN VARCHAR2
, P_CANCELLA IN VARCHAR2)
AS
ESISTE NUMBER := 0;
P_ICONA_NO VARCHAR2(50);
BEGIN
   IF P_CANCELLA = 'Y' THEN
      DELETE ETICHETTE
      WHERE AREA = P_AREA
      AND CODICE_MODELLO = P_MODELLO
      AND ETICHETTA = P_ETICHETTA;
   ELSE
      IF (P_ETICHETTA = 'STAMPA' OR P_ETICHETTA = 'ALLEGA') THEN
         P_ICONA_NO := '';
      ELSE
         P_ICONA_NO := P_ICONA;
      END IF;
      SELECT COUNT(1)
      INTO ESISTE
      FROM ETICHETTE
      WHERE AREA = P_AREA
      AND CODICE_MODELLO = P_MODELLO
      AND ETICHETTA = P_ETICHETTA
      AND (NVL(VALORE,-9999) <> NVL(P_VALORE,-9999)
      OR  NVL(ICONA,-9999) <> NVL(P_ICONA_NO,-9999));
      IF ESISTE > 0 THEN
         UPDATE ETICHETTE
         SET VALORE = P_VALORE,
         ICONA = P_ICONA_NO
         WHERE AREA = P_AREA
         AND CODICE_MODELLO = P_MODELLO
         AND ETICHETTA = P_ETICHETTA;
      ELSE
         SELECT COUNT(1)
         INTO ESISTE
         FROM ETICHETTE
         WHERE AREA = P_AREA
         AND CODICE_MODELLO = '-'
         AND ETICHETTA = P_ETICHETTA
         AND (NVL(VALORE,-9999) <> NVL(P_VALORE,-9999)
         OR  NVL(ICONA,-9999) <> NVL(P_ICONA_NO,-9999));
         IF ESISTE > 0 THEN
            INSERT INTO ETICHETTE (AREA, CODICE_MODELLO, ETICHETTA, VALORE, ICONA)
            VALUES (P_AREA, P_MODELLO, P_ETICHETTA, P_VALORE, P_ICONA_NO);
         ELSE
            SELECT COUNT(1)
            INTO ESISTE
            FROM ETICHETTE
            WHERE AREA = '-'
            AND CODICE_MODELLO = '-'
            AND ETICHETTA = P_ETICHETTA
            AND (NVL(VALORE,-9999) <> NVL(P_VALORE,-9999)
            OR  NVL(ICONA,-9999) <> NVL(P_ICONA_NO,-9999));
            IF ESISTE > 0 THEN
               INSERT INTO ETICHETTE (AREA, CODICE_MODELLO, ETICHETTA, VALORE, ICONA)
               VALUES (P_AREA, P_MODELLO, P_ETICHETTA, P_VALORE, P_ICONA_NO);
            END IF;
         END IF;
      END IF;
   END IF;
   COMMIT;
END;
/

