CREATE OR REPLACE PROCEDURE P_PULISCI_ALLEGATI_TEMP IS
BEGIN

    DELETE ALLEGATI_TEMP_PERCORSI
    WHERE trunc(sysdate - ALLEGATI_TEMP_PERCORSI.DATA_AGGIORNAMENTO )>=7;

     DELETE ALLEGATI_TEMP
    WHERE trunc(sysdate - ALLEGATI_TEMP.DATA_AGGIORNAMENTO )>=7;

    COMMIT;

   EXCEPTION
     WHEN OTHERS THEN
        ROLLBACK;
       -- Consider logging the error and then re-raise
       RAISE;
END P_PULISCI_ALLEGATI_TEMP;
/

