CREATE OR REPLACE PROCEDURE rt_rebuild_ogfi_ocr_index
IS
BEGIN
   BEGIN
      CTX_DDL.SYNC_INDEX('OGFI_OCRF_CTX','10M');
      COMMIT;
  END;
EXCEPTION
WHEN OTHERS THEN
RAISE_APPLICATION_ERROR('-20999', SQLERRM);
END;
/

