ALTER TABLE ALIAS_IN_CARTELLA ADD (
  CONSTRAINT ALCA_ALCA_FK 
  FOREIGN KEY (ID_ALIASCAMPO) 
  REFERENCES ALIAS_CAMPI (ID_ALIASCAMPO)
  ENABLE VALIDATE);

ALTER TABLE ALIAS_IN_CARTELLA ADD (
  CONSTRAINT ALIC_VWCA_FK 
  FOREIGN KEY (ID_VIEWCARTELLA) 
  REFERENCES VIEW_CARTELLA (ID_VIEWCARTELLA)
  ENABLE VALIDATE);

