ALTER TABLE AMV_DOCUMENTI_REVISIONI ADD (
  CONSTRAINT AMV_DORE_DOCU_FK 
  FOREIGN KEY (ID_DOCUMENTO, REVISIONE) 
  REFERENCES AMV_DOCUMENTI (ID_DOCUMENTO,REVISIONE)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI_REVISIONI ADD (
  CONSTRAINT AMV_DORE_UTEN_APP_FK 
  FOREIGN KEY (UTENTE_APPROVAZIONE) 
  REFERENCES AD4.UTENTI (UTENTE)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI_REVISIONI ADD (
  CONSTRAINT AMV_DORE_UTEN_RED_FK 
  FOREIGN KEY (UTENTE_REDAZIONE) 
  REFERENCES AD4.UTENTI (UTENTE)
  ENABLE VALIDATE);

ALTER TABLE AMV_DOCUMENTI_REVISIONI ADD (
  CONSTRAINT AMV_DORE_UTEN_VER_FK 
  FOREIGN KEY (UTENTE_VERIFICA) 
  REFERENCES AD4.UTENTI (UTENTE)
  ENABLE VALIDATE);

