ALTER TABLE AREE ADD (
  CONSTRAINT AREE_DIM_MAX_ALL_B_CC
  CHECK (DIM_MAX_ALL_BYTE_BLOCCANTE IN ('Y','N'))
  ENABLE VALIDATE);

ALTER TABLE AREE ADD (
  CONSTRAINT AREE_GENERAZIONE_O_CC
  CHECK (GENERAZIONE_OCR IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE AREE ADD (
  CONSTRAINT AREE_GESTIONE_MODE_CC
  CHECK (GESTIONE_MODELLI IN ('O','V'))
  ENABLE VALIDATE);

ALTER TABLE AREE ADD (
  CONSTRAINT PK_AREE
  PRIMARY KEY
  (AREA)
  USING INDEX PK_AREE
  ENABLE VALIDATE);

