ALTER TABLE AZIONI_INOLTRO ADD (
  CONSTRAINT AZIONI_INOLTR_TIPO_CC
  CHECK (TIPO IN ('P','I'))
  ENABLE VALIDATE);

ALTER TABLE AZIONI_INOLTRO ADD (
  CONSTRAINT AZIONI_INOLTRO_PK
  PRIMARY KEY
  (ID_OP, ID_PROCEDURA)
  USING INDEX AZIONI_INOLTRO_PK
  ENABLE VALIDATE);

