ALTER TABLE BLOCCHI_POPUP ADD (
  CONSTRAINT AREE_BLPO_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE BLOCCHI_POPUP ADD (
  CONSTRAINT CONN_BLPO_FK 
  FOREIGN KEY (DSN) 
  REFERENCES CONNESSIONI (DSN)
  ENABLE VALIDATE);

ALTER TABLE BLOCCHI_POPUP ADD (
  CONSTRAINT LICO_BLPO_FK 
  FOREIGN KEY (AREA, CONTROLLO_JS) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ENABLE VALIDATE);

