ALTER TABLE BLOCCHI ADD (
  CONSTRAINT BLOCCHI_PERSONALIZZAZ_CC
  CHECK (PERSONALIZZAZIONE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE BLOCCHI ADD (
  CONSTRAINT BLOCCHI_PK
  PRIMARY KEY
  (BLOCCO, AREA)
  USING INDEX BLOCCHI_PK
  ENABLE VALIDATE);

