ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CAMPI_DOCUMEN_INDICE_GENERA_CC
  CHECK (INDICE_GENERATO IN (0,1))
  ENABLE VALIDATE);

ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CAMPI_DOCUMEN_MODALITA_RICE_CC
  CHECK (MODALITA_RICERCA IN ('N','S','F'))
  ENABLE VALIDATE);

ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CAMPI_DOCUMEN_OBBLIGATORIO_CC
  CHECK (OBBLIGATORIO IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CAMPI_DOCUMENTO_PK
  PRIMARY KEY
  (ID_CAMPO)
  USING INDEX CAMPI_DOCUMENTO_PK
  ENABLE VALIDATE);

