ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CADO_ALCA_FK 
  FOREIGN KEY (ID_ALIASCAMPO) 
  REFERENCES ALIAS_CAMPI (ID_ALIASCAMPO)
  ENABLE VALIDATE);

ALTER TABLE CAMPI_DOCUMENTO ADD (
  CONSTRAINT CADO_TIDO 
  FOREIGN KEY (ID_TIPODOC) 
  REFERENCES TIPI_DOCUMENTO (ID_TIPODOC)
  ON DELETE CASCADE
  ENABLE VALIDATE);

