ALTER TABLE CARTELLE ADD (
  CONSTRAINT CARTELLE_TIPO_CC
  CHECK (TIPO IN ('S','U'))
  ENABLE VALIDATE);

ALTER TABLE CARTELLE ADD (
  CONSTRAINT CARTELLE_PK
  PRIMARY KEY
  (ID_CARTELLA)
  USING INDEX CARTELLE_PK
  ENABLE VALIDATE);

