ALTER TABLE CONTROLLI_CARTELLE ADD (
  CONSTRAINT LICO_COCA_FK 
  FOREIGN KEY (AREA, CONTROLLO) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ENABLE VALIDATE);

ALTER TABLE CONTROLLI_CARTELLE ADD (
  CONSTRAINT RISO_COCA_FK 
  FOREIGN KEY (ID_RISORSA) 
  REFERENCES RISORSE (ID_RISORSA)
  ENABLE VALIDATE);

