ALTER TABLE CONTROLLI_DATI ADD (
  CONSTRAINT CODA_DATI_FK 
  FOREIGN KEY (AREA, DATO) 
  REFERENCES DATI (AREA,DATO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE CONTROLLI_DATI ADD (
  CONSTRAINT CODA_EVEN_FK 
  FOREIGN KEY (EVENTO) 
  REFERENCES EVENTI (EVENTO)
  ENABLE VALIDATE);

ALTER TABLE CONTROLLI_DATI ADD (
  CONSTRAINT LICO_CODA_FK 
  FOREIGN KEY (AREA, CONTROLLO) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

