ALTER TABLE CONTROLLI_MODELLI ADD (
  CONSTRAINT COMO_EVEN_FK 
  FOREIGN KEY (EVENTO) 
  REFERENCES EVENTI (EVENTO)
  ENABLE VALIDATE);

ALTER TABLE CONTROLLI_MODELLI ADD (
  CONSTRAINT LICO_COMO_FK 
  FOREIGN KEY (AREA, CONTROLLO) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE CONTROLLI_MODELLI ADD (
  CONSTRAINT MODE_COMO_FK 
  FOREIGN KEY (AREA, CODICE_MODELLO) 
  REFERENCES MODELLI (AREA,CODICE_MODELLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

