ALTER TABLE DM_ERR_LOG_USERLEVEL ADD (
  CONSTRAINT DM_ERR_LOG_US_LIVELLO_CC
  CHECK (LIVELLO IN (0,1,2,3))
  ENABLE VALIDATE);

ALTER TABLE DM_ERR_LOG_USERLEVEL ADD (
  CONSTRAINT DM_ERR_LOG_USERLEVEL_PK
  PRIMARY KEY
  (UTENTE, CATEGORIA)
  USING INDEX DM_ERR_LOG_USERLEVEL_PK
  ENABLE VALIDATE);

