ALTER TABLE DM_ERR_LOG_RIGHE ADD (
  CONSTRAINT DM_ERR_LOG_RI_LIVELLO_CC
  CHECK (LIVELLO IN (1,2,3))
  ENABLE VALIDATE);

ALTER TABLE DM_ERR_LOG_RIGHE ADD (
  CONSTRAINT DM_ERR_LOG_RIGHE_PK
  PRIMARY KEY
  (SEQUENZA, ID_ERR_LOG)
  USING INDEX DM_ERR_LOG_RIGHE_PK
  ENABLE VALIDATE);

