ALTER TABLE DOCUMENTI ADD (
  CONSTRAINT DOCU_TIDO_FK 
  FOREIGN KEY (ID_TIPODOC) 
  REFERENCES TIPI_DOCUMENTO (ID_TIPODOC)
  ENABLE VALIDATE);

ALTER TABLE DOCUMENTI ADD (
  CONSTRAINT ID_DOCPADRE_FK 
  FOREIGN KEY (ID_DOCUMENTO_PADRE) 
  REFERENCES DOCUMENTI (ID_DOCUMENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE DOCUMENTI ADD (
  CONSTRAINT LIBR_DOCU_FK 
  FOREIGN KEY (ID_LIBRERIA) 
  REFERENCES LIBRERIE (ID_LIBRERIA)
  ENABLE VALIDATE);

ALTER TABLE DOCUMENTI ADD (
  CONSTRAINT RICH_DOCU_FK 
  FOREIGN KEY (CODICE_RICHIESTA, AREA) 
  REFERENCES RICHIESTE (CODICE_RICHIESTA,AREA)
  ENABLE VALIDATE);

