ALTER TABLE DOMINI ADD (
  CONSTRAINT AREE_DOMI_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ENABLE VALIDATE);

ALTER TABLE DOMINI ADD (
  CONSTRAINT CONN_DOMI_FK 
  FOREIGN KEY (DSN) 
  REFERENCES CONNESSIONI (DSN)
  ENABLE VALIDATE);

ALTER TABLE DOMINI ADD (
  CONSTRAINT TIDO_DOMI_FK 
  FOREIGN KEY (TIPO) 
  REFERENCES TIPI_DOMINIO (TIPO_DOMINIO_ID)
  ENABLE VALIDATE);

