ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ICON_ETIC_FK 
  FOREIGN KEY (ICONA) 
  REFERENCES ICONE (ICONA)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ICON_ETI2_FK 
  FOREIGN KEY (ICONA_DS) 
  REFERENCES ICONE (ICONA)
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT LICO_ETIC_FK 
  FOREIGN KEY (AREA, CONTROLLO) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT LICO_ETI2_FK 
  FOREIGN KEY (AREA, CONTROLLO_JS) 
  REFERENCES LIBRERIA_CONTROLLI (AREA,CONTROLLO)
  ENABLE VALIDATE);

