ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ETICHETTE_PERSONALIZZAZ_CC
  CHECK (PERSONALIZZAZIONE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ETICHETTE_SALVATAGGIO_CC
  CHECK (SALVATAGGIO IS NULL OR (SALVATAGGIO IN ('NO','PS','DS','PR','DR')))
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ETICHETTE_SEPARATORE_CC
  CHECK (SEPARATORE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ETICHETTE_TIPO_USO_CC
  CHECK (TIPO_USO IN ('C','E','X'))
  ENABLE VALIDATE);

ALTER TABLE ETICHETTE ADD (
  CONSTRAINT ETICHETTE_PK
  PRIMARY KEY
  (AREA, CODICE_MODELLO, ETICHETTA)
  USING INDEX ETICHETTE_PK
  ENABLE VALIDATE);

