ALTER TABLE FORMATI_FILE ADD (
  CONSTRAINT FORMATI_FILE_VISIBILE_CC
  CHECK (VISIBILE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE FORMATI_FILE ADD (
  CONSTRAINT FORMATI_FILE_PK
  PRIMARY KEY
  (ID_FORMATO)
  USING INDEX FORMATI_FILE_PK
  ENABLE VALIDATE);

