ALTER TABLE FORMATI_VIEWER ADD (
  CONSTRAINT FOFI_FOVI_FK 
  FOREIGN KEY (ID_FORMATO) 
  REFERENCES FORMATI_FILE (ID_FORMATO)
  ENABLE VALIDATE);

ALTER TABLE FORMATI_VIEWER ADD (
  CONSTRAINT VIEW_FOVI_FK 
  FOREIGN KEY (ID_VIEWER) 
  REFERENCES VIEWER (ID_VIEWER)
  ENABLE VALIDATE);

