ALTER TABLE FRASI_GLOSSARIO ADD (
  CONSTRAINT FRASI_GLOSSAR_PARAMETRICA_CC
  CHECK (PARAMETRICA IS NULL OR (PARAMETRICA IN ('N','S')))
  ENABLE VALIDATE);

ALTER TABLE FRASI_GLOSSARIO ADD (
  CONSTRAINT FRASI_GLOSSARIO_PK
  PRIMARY KEY
  (ID_FRASE)
  USING INDEX FRASI_GLOSSARIO_PK
  ENABLE VALIDATE);

