ALTER TABLE INDICI_DOCUMENTO ADD (
  CONSTRAINT INDICI_DOCUME_FORMATO_CC
  CHECK (FORMATO IN ('C','F'))
  ENABLE VALIDATE);

ALTER TABLE INDICI_DOCUMENTO ADD (
  CONSTRAINT INDICI_DOCUME_STATO_CC
  CHECK (STATO IN ('N','C','M','D'))
  ENABLE VALIDATE);

ALTER TABLE INDICI_DOCUMENTO ADD (
  CONSTRAINT INDICI_DOCUMENTO_PK
  PRIMARY KEY
  (INDICE, ID_TIPODOC)
  USING INDEX INDICI_DOCUMENTO_PK
  ENABLE VALIDATE);

