ALTER TABLE LIBRERIA_CONTROLLI ADD (
  CONSTRAINT LIBRERIA_CONT_PERSONALIZZAZ_CC
  CHECK (PERSONALIZZAZIONE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE LIBRERIA_CONTROLLI ADD (
  CONSTRAINT LIBRERIA_CONTROLLI_PK
  PRIMARY KEY
  (AREA, CONTROLLO)
  USING INDEX LIBRERIA_CONTROLLI_PK
  ENABLE VALIDATE);

