ALTER TABLE LINKS ADD (
  CONSTRAINT LINKS_TIPO_OGGETTO_CC
  CHECK (TIPO_OGGETTO IN ('D','Q','C','L'))
  ENABLE VALIDATE);

ALTER TABLE LINKS ADD (
  CONSTRAINT LINKS_PK
  PRIMARY KEY
  (ID_LINK)
  USING INDEX LINKS_PK
  ENABLE VALIDATE);

