ALTER TABLE LOG_INOLTRI ADD (
  CONSTRAINT LOG_INOLTRI_STATO_CC
  CHECK (STATO IS NULL OR (STATO IN (0,1)))
  ENABLE VALIDATE);

ALTER TABLE LOG_INOLTRI ADD (
  CONSTRAINT LOG_INOLTRI_PK
  PRIMARY KEY
  (CODICE_RICHIESTA, AREA, ID_OP)
  USING INDEX LOG_INOLTRI_PK
  ENABLE VALIDATE);

