ALTER TABLE MODELLI ADD (
  CONSTRAINT MODELLI_DIM_MAX_ALL_B_CC
  CHECK (DIM_MAX_ALL_BYTE_BLOCCANTE in ('Y','N'))
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT MODELLI_GENERAZIONE_O_CC
  CHECK (GENERAZIONE_OCR in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT MODELLI_POS_PULSANTI_CC
  CHECK (POS_PULSANTI in ('A','B'))
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT MODELLI_TIPO_USO_CC
  CHECK (TIPO_USO in ('D','P','X','N','C','Q','F','V','W','R'))
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT PK_MODELLI
  PRIMARY KEY
  (AREA, CODICE_MODELLO)
  USING INDEX PK_MODELLI
  ENABLE VALIDATE);

