ALTER TABLE MODELLI ADD (
  CONSTRAINT AREE_MODE_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT MODE_MODE_FK 
  FOREIGN KEY (AREA, CODICE_MODELLO_PADRE) 
  REFERENCES MODELLI (AREA,CODICE_MODELLO)
  ENABLE VALIDATE);

ALTER TABLE MODELLI ADD (
  CONSTRAINT TIDO_MODE_FK 
  FOREIGN KEY (ID_TIPODOC) 
  REFERENCES TIPI_DOCUMENTO (ID_TIPODOC)
  ENABLE VALIDATE);

