ALTER TABLE OGGETTI_FILE ADD (
  CONSTRAINT OGGETTI_FILE_ALLEGATO_CC
  CHECK (ALLEGATO IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE OGGETTI_FILE ADD (
  CONSTRAINT OGGETTI_FILE_DA_CANCELLARE_CC
  CHECK (DA_CANCELLARE IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE OGGETTI_FILE ADD (
  CONSTRAINT OGGETTI_FILE_OCR_PENDING_CC
  CHECK (OCR_PENDING IS NULL OR (OCR_PENDING IN (-1,0,1)))
  ENABLE VALIDATE);

ALTER TABLE OGGETTI_FILE ADD (
  CONSTRAINT OGGETTI_FILE_PK
  PRIMARY KEY
  (ID_OGGETTO_FILE)
  USING INDEX OGGETTI_FILE_PK
  ENABLE VALIDATE);

