ALTER TABLE OPERAZIONI_DI_INOLTRO ADD (
  CONSTRAINT AREE_OPIN_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ENABLE VALIDATE);

ALTER TABLE OPERAZIONI_DI_INOLTRO ADD (
  CONSTRAINT CONN_OPIN_FK 
  FOREIGN KEY (DSN) 
  REFERENCES CONNESSIONI (DSN)
  ENABLE VALIDATE);

ALTER TABLE OPERAZIONI_DI_INOLTRO ADD (
  CONSTRAINT MODE_OPIN_FK 
  FOREIGN KEY (AREA, CODICE_MODELLO) 
  REFERENCES MODELLI (AREA,CODICE_MODELLO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE OPERAZIONI_DI_INOLTRO ADD (
  CONSTRAINT TIPR_OPIN_FK 
  FOREIGN KEY (ID_TIPO_PRATICA) 
  REFERENCES TIPI_PRATICHE (ID_TIPO_PRATICA)
  ON DELETE CASCADE
  ENABLE VALIDATE);

