ALTER TABLE PARAMETRI_POPUP ADD (
  CONSTRAINT PARAMETRI_POP_TIPO_CC
  CHECK (TIPO IN ('R','F'))
  ENABLE VALIDATE);

ALTER TABLE PARAMETRI_POPUP ADD (
  CONSTRAINT PARAMETRI_POPUP_PK
  PRIMARY KEY
  (AREA, BLOCCO, PARAMETRO)
  USING INDEX PARAMETRI_POPUP_PK
  ENABLE VALIDATE);

