ALTER TABLE PERSONALIZZAZIONI ADD (
  CONSTRAINT PERSONALIZZAZ_ATTIVO_CC
  CHECK (ATTIVO IN ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE PERSONALIZZAZIONI ADD (
  CONSTRAINT PERSONALIZZAZIONI_PK
  PRIMARY KEY
  (ID_PERSONALIZZAZIONE)
  USING INDEX PERSONALIZZAZIONI_PK
  ENABLE VALIDATE);

