ALTER TABLE RICHIESTE ADD (
  CONSTRAINT AREE_RICH_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ENABLE VALIDATE);

ALTER TABLE RICHIESTE ADD (
  CONSTRAINT TIPR_RICH_FK 
  FOREIGN KEY (ID_TIPO_PRATICA) 
  REFERENCES TIPI_PRATICHE (ID_TIPO_PRATICA)
  ENABLE VALIDATE);

