ALTER TABLE RIFERIMENTI ADD (
  CONSTRAINT RELA_DOCU_1 
  FOREIGN KEY (ID_DOCUMENTO) 
  REFERENCES DOCUMENTI (ID_DOCUMENTO)
  ENABLE VALIDATE);

ALTER TABLE RIFERIMENTI ADD (
  CONSTRAINT RELA_DOCU_2 
  FOREIGN KEY (ID_DOCUMENTO_RIF) 
  REFERENCES DOCUMENTI (ID_DOCUMENTO)
  ENABLE VALIDATE);

ALTER TABLE RIFERIMENTI ADD (
  CONSTRAINT TIPO_RELA_FK 
  FOREIGN KEY (AREA, TIPO_RELAZIONE) 
  REFERENCES TIPI_RELAZIONE (AREA,TIPO_RELAZIONE)
  ENABLE VALIDATE);

