ALTER TABLE STATI_DOCUMENTO ADD (
  CONSTRAINT STATI_DOCUMEN_STATO_CC
  CHECK (STATO IN ('BO','SO','CO','AN','PU','PR','A','RE','I','O','AR','PB','CA'))
  ENABLE VALIDATE);

ALTER TABLE STATI_DOCUMENTO ADD (
  CONSTRAINT STATI_DOCUMENTO_PK
  PRIMARY KEY
  (ID_STATO)
  USING INDEX STATI_DOCUMENTO_PK
  ENABLE VALIDATE);

