ALTER TABLE SYSINTEGRATION_MODEL ADD (
  CONSTRAINT SYSINTEGRATIO_LOGITEM_CC
  CHECK (LOGITEM IN ('H','L','O'))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_MODEL ADD (
  CONSTRAINT SYSINTEGRATION_MODEL_PK
  PRIMARY KEY
  (TYPE_INTEGRATION, AREA, CODICE_MODELLO)
  USING INDEX SYSINTEGRATION_MODEL_PK
  ENABLE VALIDATE);

