ALTER TABLE SYSINTEGRATION_FIELD ADD (
  CONSTRAINT SYSINTEGRATIO_ACTIVE_CC
  CHECK (ACTIVE IN (1,0))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_FIELD ADD (
  CONSTRAINT SYSINTEGRATIO_KEYFIELD_CC
  CHECK (KEYFIELD IN (1,0))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_FIELD ADD (
  CONSTRAINT SYSINTEGRATION_FIELD_PK
  PRIMARY KEY
  (TYPE_INTEGRATION, AREA, CODICE_MODELLO, FIELD)
  USING INDEX SYSINTEGRATION_FIELD_PK
  ENABLE VALIDATE);

