ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT SYSINTEGRATIO_EXPORTFIELD_CC
  CHECK (EXPORTFIELD IN (1,0))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT SYSINTEGRATIO_LASTSTATUS_CC
  CHECK (LASTSTATUS IN ('OK','ER','WT'))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT SYSINTEGRATIO_PENDING_CC
  CHECK (PENDING IN (1,0))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT SYSINTEGRATION_PENDING_PK
  PRIMARY KEY
  (IDSYSPENDING)
  USING INDEX SYSINTEGRATION_PENDING_PK
  ENABLE VALIDATE);

