ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT DOCU_SYPE_FK 
  FOREIGN KEY (ID_DOCUMENTO) 
  REFERENCES DOCUMENTI (ID_DOCUMENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING ADD (
  CONSTRAINT SYTY_SYPE_FK 
  FOREIGN KEY (TYPE_INTEGRATION) 
  REFERENCES SYSINTEGRATION_TYPE (TYPE_INTEGRATION)
  ENABLE VALIDATE);

