ALTER TABLE SYSINTEGRATION_PENDING_LOG ADD (
  CONSTRAINT SYSINTEGRATIO_ACTION_CC
  CHECK (ACTION IN ('C','M'))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING_LOG ADD (
  CONSTRAINT SYSINTEGRATIO_RESULT_CC
  CHECK (RESULT IN ('ER','OK'))
  ENABLE VALIDATE);

ALTER TABLE SYSINTEGRATION_PENDING_LOG ADD (
  CONSTRAINT SYSINTEGRATION_PENDING_LOG_PK
  PRIMARY KEY
  (IDLOGPENDING)
  USING INDEX SYSINTEGRATION_PENDING_LOG_PK
  ENABLE VALIDATE);

