ALTER TABLE TIPI_RELAZIONE ADD (
  CONSTRAINT TIPI_RELAZION_DIPENDENZA_CC
  CHECK (DIPENDENZA IS NULL OR (DIPENDENZA IN ('S','N')))
  ENABLE VALIDATE);

ALTER TABLE TIPI_RELAZIONE ADD (
  CONSTRAINT TIPI_RELAZION_VISIBILE_CC
  CHECK (VISIBILE IS NULL OR (VISIBILE IN ('S','N')))
  ENABLE VALIDATE);

ALTER TABLE TIPI_RELAZIONE ADD (
  CONSTRAINT TIPI_RELAZIONE_PK
  PRIMARY KEY
  (AREA, TIPO_RELAZIONE)
  USING INDEX TIPI_RELAZIONE_PK
  ENABLE VALIDATE);

