ALTER TABLE TIPI_PRATICHE ADD (
  CONSTRAINT AREE_TIPR_FK 
  FOREIGN KEY (AREA) 
  REFERENCES AREE (AREA)
  ENABLE VALIDATE);

ALTER TABLE TIPI_PRATICHE ADD (
  CONSTRAINT MODE_TIPR_FK 
  FOREIGN KEY (MOD_AREA, CODICE_MODELLO) 
  REFERENCES MODELLI (AREA,CODICE_MODELLO)
  ENABLE VALIDATE);

