ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_ATTIVAPRATICA_CC
  CHECK (ATTIVAPRATICA in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_COMPETENZE_AL_CC
  CHECK (COMPETENZE_ALLEGATI in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_GESTIONE_COMP_CC
  CHECK (GESTIONE_COMPETENZE in ('0','1','2','3','4','5','6'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_LOG_FILE_CC
  CHECK (LOG_FILE is null or (LOG_FILE in ('S','N')))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_MANAGE_COMPET_CC
  CHECK (MANAGE_COMPETENZE in ('0','1','2'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_TIPO_LOG_CC
  CHECK (TIPO_LOG in ('N','S','M','V','X'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENT_VERSIONABILE_CC
  CHECK (VERSIONABILE in ('S','N'))
  ENABLE VALIDATE);

ALTER TABLE TIPI_DOCUMENTO ADD (
  CONSTRAINT TIPI_DOCUMENTO_PK
  PRIMARY KEY
  (ID_TIPODOC)
  USING INDEX TIPI_DOCUMENTO_PK
  ENABLE VALIDATE);

