ALTER TABLE VALORI ADD (
  CONSTRAINT VALO_CADO 
  FOREIGN KEY (ID_CAMPO) 
  REFERENCES CAMPI_DOCUMENTO (ID_CAMPO)
  ENABLE VALIDATE);

ALTER TABLE VALORI ADD (
  CONSTRAINT VALO_DOCU 
  FOREIGN KEY (ID_DOCUMENTO) 
  REFERENCES DOCUMENTI (ID_DOCUMENTO)
  ON DELETE CASCADE
  ENABLE VALIDATE);

